base_images:
  upi-installer:
    name: "4.8"
    namespace: origin
    tag: upi-installer
releases:
  latest:
    candidate:
      product: okd
      stream: okd
      version: "4.8"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 32 8 9,20 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.8
