base_images:
  upi-installer:
    name: "4.6"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    release:
      channel: candidate
      version: "4.6"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.7"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 32 5 5,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cron: 51 4 8,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 15 6 10,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-vsphere-upgrade
  cron: 58 9 7,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-upgrade-vsphere
- as: e2e-ovirt-upgrade
  cron: 52 1 8,16 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-upgrade-ovirt-release-4.6-4.7
- as: e2e-aws-ovn-upgrade
  cron: 52 7 10,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-gcp-ovn-upgrade
  cron: 9 8 9,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp-ovn
- as: e2e-azure-ovn-upgrade
  cron: 36 10 8,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-aws-uwm
  cron: 29 5 5,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    pre:
    - ref: ipi-conf-user-workload-monitoring
    - chain: ipi-aws-pre-stableinitial
    workflow: openshift-upgrade-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.7-upgrade-from-stable-4.6
