releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.1'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.1'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 41 8 5,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 25 10 10,24 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.1
