releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.4'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.4'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-gcp-upgrade
  cron: 43 4 7,21 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 5 4 8,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-upgrade-azure
- as: e2e-aws
  cron: 52 7 10,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 28 9 8,21 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws-sdn-multitenant
  cron: 17 9 6,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-serial
  cron: 11 5 5,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.4
