releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.13'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 24 3 * * 6
- as: e2e-aws-sdn-techpreview
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 35 12 * * 7
- as: e2e-aws-ovn-no-capabilities
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      BASELINE_CAPABILITY_SET: None
      PERSISTENT_MONITORING: 'false'
      TEST_SKIPS: check registry.redhat.io is available and samples operator can import
        sample imagestreams
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
  cron: 19 20 * * 7
- as: e2e-aws-ovn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
  cron: 55 22 * * 7
- as: e2e-aws-sdn-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
  cron: 41 13 * * 6
- as: e2e-aws-ovn-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
  cron: 3 17 * * 6
- as: e2e-aws-sdn-techpreview-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
  cron: 50 15 * * 7
- as: e2e-aws-sdn-multitenant
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-multi
  cron: 25 16 * * 6
- as: e2e-aws-sdn-upgrade
  cluster: build01
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
  cron: 26 7 * * 6
- as: e2e-aws-ovn-upgrade
  cluster: build01
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
  cron: 43 14 * * 7
- as: e2e-aws-cilium
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-cilium
  cron: 5 21 * * 7
- as: e2e-aws-sdn-imdsv2
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
  cron: 14 17 * * 6
- as: e2e-azure-sdn
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
  cron: 23 20 * * 6
- as: e2e-azure-sdn-techpreview
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
  cron: 58 7 * * 6
- as: e2e-azure-sdn-serial
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
  cron: 13 20 * * 6
- as: e2e-azure-sdn-techpreview-serial
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
  cron: 42 1 * * 6
- as: e2e-azure-sdn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-sdn
  cron: 43 17 * * 6
- as: e2e-azure-ovn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  cron: 0 12 * * 7
- as: e2e-azure-cilium
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-cilium
  cron: 26 17 * * 6
- as: e2e-azure-ovn
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
  cron: 41 4 * * 7
- as: e2e-gcp-sdn
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
  cron: 51 20 * * 7
- as: e2e-gcp-sdn-techpreview
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
  cron: 42 14 * * 6
- as: e2e-gcp-ovn
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
  cron: 38 8 * * 7
- as: e2e-gcp-ovn-mount-ns-hiding
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
      MOUNT_NS_HIDING_ENABLED: 'true'
      MOUNT_NS_HIDING_LOG: '2'
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-mount-ns-hiding
  cron: 18 9 * * 7
- as: e2e-gcp-sdn-techpreview-serial
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
  cron: 40 20 * * 6
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-sdn
  cron: 46 6 * * 6
- as: e2e-gcp-cilium
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-cilium
  cron: 59 8 * * 7
- as: e2e-gcp-secureboot
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-secureboot
  timeout: 6h0m0s
  cron: 42 13 * * 6
- as: e2e-aws-sdn-upgrade-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
  cron: 52 15 * * 7
- as: e2e-aws-upgrade-ovn-single-node
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-single-node
  cron: 15 14 * * 6
- as: e2e-aws-ovn-network-migration
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
  cron: 40 4 * * 6
- as: e2e-network-migration-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
  cron: 58 3 * * 6
- as: e2e-aws-sdn-cgroupsv2
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-cgroupsv2
  cron: 6 14 * * 7
- as: e2e-aws-sdn-crun
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-crun
  cron: 42 16 * * 6
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.13
