releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.5"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.5"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-gcp-upgrade
  cron: 44 1 8,25 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
- as: e2e-azure-ovn
  cron: 51 1 6,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-ovn
- as: e2e-azure-upgrade
  cron: 1 2 6,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-upgrade-azure
- as: e2e-aws
  cron: 55 8 7,17 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-ovn
  cron: 13 7 7,15 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-ovn
- as: e2e-gcp
  cron: 50 7 7,15 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-gcp-ovn
  cron: 45 5 9,17 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-ovn
- as: e2e-aws-upgrade-rollback
  cron: 25 2 5,15 * *
  steps:
    cluster_profile: aws
    env:
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws-sdn-multitenant
  cron: 53 1 8,24 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-serial
  cron: 59 3 5,17 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.5
