releases:
  initial:
    candidate:
      product: okd
      stream: okd
      version: "4.10"
  latest:
    candidate:
      product: okd
      stream: okd
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-upgrade-aws
  cron: 31 6 6,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-upgrade-aws
- as: e2e-upgrade-gcp
  cron: 54 9 5,21 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.11-upgrade-from-okd-4.10
