releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.3'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.3'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn-multitenant
  cron: 52 6 10,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-gcp
  cron: 17 5 5,22 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws
  cron: 21 10 6,16 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 32 7 7,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.3
