base_images:
  ansible:
    name: "4.6"
    namespace: ocp
    tag: ansible
  base:
    name: "4.6"
    namespace: ocp
    tag: base
  cluster-logging-operator-e2e:
    name: "4.6"
    namespace: ocp
    tag: cluster-logging-operator-e2e
  console-tests:
    name: "4.6"
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  libvirt-installer:
    name: "4.6"
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: "4.6"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.6"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.6"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-proxy
  cron: 40 6 5,20 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-vsphere
  cron: 34 3 5,18 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-release46
- as: e2e-vsphere-serial
  cron: 52 8 7,15 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-serial
- as: e2e-vsphere-upi
  cron: 45 4 6,20 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-release46
- as: e2e-vsphere-upi-serial
  cron: 43 7 6,15 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-serial
- as: e2e-aws-workers-rhel7
  cron: 42 9 7,23 * *
  steps:
    cluster_profile: aws
    env:
      PLATFORM_VERSION: "7.9"
    workflow: openshift-e2e-aws-workers-rhel
- as: e2e-aws
  cron: 15 4 9,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-gcp-libvirt-cert-rotation
  cron: 56 6 5,18 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-libvirt-cert-rotation
- as: e2e-gcp
  cron: 15 4 8,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 16 5 10,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: cluster-logging-operator-e2e
  cron: 38 7 6,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: FAKE_HOME_DIR=/tmp/home LOG_DIR=${ARTIFACT_DIR}/logging-logs ARTIFACT_DIR=${ARTIFACT_DIR}/logging-artifacts
        make test-e2e-olm
      from: cluster-logging-operator-e2e
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 43 5 8,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 24 3 5,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 46 2 7,22 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 9 2 9,18 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 3 9 6,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 57 8 6,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp-rt
  cron: 47 6 10,20 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      RT_ENABLED: "true"
    workflow: openshift-e2e-gcp-realtime
- as: e2e-aws-serial
  cron: 23 2 7,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 51 3 6,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.6
