base_images:
  base:
    name: '4.4'
    namespace: ocp
    tag: base
  console-tests:
    name: '4.4'
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  upi-installer:
    name: '4.4'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.4'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.4'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-proxy
  cron: 42 2 8,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-aws
  cron: 22 1 5,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-upgrade
  cron: 39 4 9,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws
- as: e2e-gcp
  cron: 33 4 10,22 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 13 8 7,16 * *
  steps:
    cluster_profile: aws
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 58 9 10,20 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 50 7 10,22 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 59 5 7,24 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 18 1 10,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 39 8 8,18 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 28 1 9,15 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-aws-fips-upgrade
  cron: 59 3 10,20 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-upgrade-aws
- as: e2e-aws-serial
  cron: 25 9 6,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 32 8 10,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.4
