base_images:
  console-tests:
    name: '4.2'
    namespace: ocp
    tag: console-tests
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.2'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.2'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: console-aws
  cron: 54 3 5,23 * *
  steps:
    cluster_profile: aws
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 50 8 10,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 21 9 5,19 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 19 10 6,17 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 41 3 9,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 36 1 10,20 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 4 9 9,17 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp
  cron: 46 1 5,19 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws
  cron: 25 1 10,16 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 16 9 5,22 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 41 2 5,25 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.2
