releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn
  cron: 14 3 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-sdn-techpreview
  cron: 41 12 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-ovn-no-capabilities
  cron: 43 17 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      BASELINE_CAPABILITY_SET: None
      PERSISTENT_MONITORING: "false"
      TEST_SKIPS: check registry.redhat.io is available and samples operator can import
        sample imagestreams
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-ovn
  cron: 10 8 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-sdn-serial
  cron: 44 14 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
- as: e2e-aws-ovn-serial
  cron: 17 12 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-sdn-techpreview-serial
  cron: 25 4 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-serial
- as: e2e-aws-sdn-multitenant
  cron: 37 9 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-sdn-upgrade
  cluster: build01
  cron: 42 22 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 13 17 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  cron: 44 2 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-cilium
- as: e2e-aws-sdn-imdsv2
  cron: 6 12 * * 6
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn
- as: e2e-azure-sdn
  cron: 22 9 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
- as: e2e-azure-sdn-techpreview
  cron: 37 10 * * 6
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn
- as: e2e-azure-sdn-serial
  cron: 26 1 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
- as: e2e-azure-sdn-techpreview-serial
  cron: 48 8 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-sdn-serial
- as: e2e-azure-sdn-upgrade
  cron: 51 2 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-sdn
- as: e2e-azure-ovn-upgrade
  cron: 24 20 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  cron: 31 11 * * 0
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 47 20 * * 6
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp-sdn
  cron: 21 3 * * 6
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
- as: e2e-gcp-sdn-techpreview
  cron: 41 21 * * 6
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn
- as: e2e-gcp-ovn
  cron: 24 12 * * 0
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-ovn-mount-ns-hiding
  cron: 6 19 * * 0
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
      MOUNT_NS_HIDING_ENABLED: "true"
      MOUNT_NS_HIDING_LOG: "2"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-mount-ns-hiding
- as: e2e-gcp-sdn-techpreview-serial
  cron: 33 21 * * 6
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-sdn-serial
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  cron: 41 14 * * 0
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-sdn
- as: e2e-gcp-cilium
  cron: 59 20 * * 0
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-cilium
- as: e2e-gcp-secureboot
  cron: 41 11 * * 6
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-secureboot
  timeout: 6h0m0s
- as: e2e-aws-sdn-upgrade-rollback
  cron: 57 19 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
- as: e2e-aws-upgrade-ovn-single-node
  cron: 10 6 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-single-node
- as: e2e-aws-ovn-network-migration
  cron: 28 16 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
- as: e2e-network-migration-rollback
  cron: 1 18 * * 0
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    observers:
      enable:
      - observers-resource-watch
    test:
    - ref: ovn-sdn-migration-feature-migration-config-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-config-egress-ip
    - ref: ovn-sdn-migration-feature-migration-config-multicast
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: ovn-sdn-migration-feature-migration-validate-egress-firewall
    - ref: ovn-sdn-migration-feature-migration-validate-egress-ip
    - ref: ovn-sdn-migration-feature-migration-validate-multicast
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-sdn
- as: e2e-aws-sdn-cgroupsv2
  cron: 2 15 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-cgroupsv2
- as: e2e-aws-sdn-crun
  cron: 57 11 * * 6
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-sdn-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.13
