releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.9"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.9"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 25 3 6,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-techpreview
  cron: 27 8 5,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview
- as: e2e-aws-ovn
  cron: 33 10 6,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-serial
  cron: 36 9 8,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-techpreview-serial
  cron: 29 8 6,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview-serial
- as: e2e-aws-sdn-multitenant
  cron: 10 1 6,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-upgrade
  cluster: build01
  cron: 45 6 10,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws-cilium
  cron: 1 10 10,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cilium
- as: e2e-azure
  cron: 5 7 5,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-techpreview
  cron: 54 3 5,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview
- as: e2e-azure-serial
  cron: 35 6 9,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-serial
- as: e2e-azure-techpreview-serial
  cron: 9 4 6,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview-serial
- as: e2e-azure-upgrade
  cron: 19 6 10,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-azure-cilium
  cron: 29 4 10,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 38 6 5,20 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp
  cron: 56 5 9,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-ovn
  cron: 31 3 6,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-upgrade
  cluster: build02
  cron: 39 2 10,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-gcp-cilium
  cron: 6 2 5,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-cilium
- as: e2e-aws-upgrade-rollback
  cron: 19 3 9,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-ovn-single-node
  cron: 30 5 5,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: ""
      TEST_SUITE: ""
      TEST_TYPE: upgrade
      TEST_UPGRADE_OPTIONS: ""
      TEST_UPGRADE_SUITE: none
    workflow: openshift-upgrade-aws-single-node
- as: e2e-network-migration
  cron: 7 2 8,15 * *
  steps:
    cluster_profile: aws
    env:
      TEST_SKIPS: Alerts shouldn't report any alerts in firing or pending state\|
        Prometheus when installed on the cluster shouldn't report any alerts in firing
        state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-network-migration-rollback
  cron: 30 8 7,20 * *
  steps:
    cluster_profile: aws
    env:
      TEST_SKIPS: Alerts shouldn't report any alerts in firing or pending state\|
        Prometheus when installed on the cluster shouldn't report any alerts in firing
        state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.9
