releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.10'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.10'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 5 8 5,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-techpreview
  cron: 2 10 10,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview
- as: e2e-aws-ovn
  cron: 35 2 8,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-serial
  cron: 12 1 8,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-techpreview-serial
  cron: 44 3 5,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview-serial
- as: e2e-aws-sdn-multitenant
  cron: 26 10 5,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-upgrade
  cluster: build01
  cron: 1 9 7,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 27 5 6,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  cron: 2 1 10,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cilium
- as: e2e-azure
  cron: 52 9 5,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-techpreview
  cron: 18 6 10,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview
- as: e2e-azure-serial
  cron: 1 2 6,18 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-serial
- as: e2e-azure-techpreview-serial
  cron: 53 1 5,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview-serial
- as: e2e-azure-upgrade
  cron: 38 9 5,25 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-azure-ovn-upgrade
  cron: 53 8 7,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  cron: 2 2 5,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 54 1 5,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp
  cron: 45 9 7,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-techpreview
  cron: 12 1 9,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview
- as: e2e-gcp-ovn
  cron: 39 10 10,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-techpreview-serial
  cron: 26 3 9,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview-serial
- as: e2e-gcp-upgrade
  cluster: build02
  cron: 14 7 5,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-gcp-cilium
  cron: 13 10 10,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-cilium
- as: e2e-aws-upgrade-rollback
  cron: 29 2 5,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-ovn-single-node
  cron: 31 10 9,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-single-node
- as: e2e-network-migration
  cron: 19 3 10,25 * *
  steps:
    cluster_profile: aws
    env:
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-network-migration-rollback
  cron: 50 10 10,24 * *
  steps:
    cluster_profile: aws
    env:
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-aws-cgroupsv2
  cron: 31 6 8,17 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-crun
  cron: 34 3 10,16 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.10
