base_images:
  console-tests:
    name: '4.3'
    namespace: ocp
    tag: console-tests
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.3'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.3'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: console-aws
  cron: 39 6 10,19 * *
  steps:
    cluster_profile: aws
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 1 9 10,18 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 47 2 6,17 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 25 7 6,22 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 32 2 9,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 52 4 5,23 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 51 5 7,19 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp
  cron: 51 10 9,21 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws-fips-upgrade
  cron: 40 1 10,17 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-upgrade-aws
- as: e2e-aws
  cron: 18 4 8,17 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 33 10 7,23 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 17 4 9,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.3
