base_images:
  upi-installer:
    name: '4.13'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    release:
      channel: candidate
      version: '4.12'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-sdn
  cron: 26 19 * * 7
- as: e2e-gcp-sdn-upgrade
  cluster: build02
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-sdn
  cron: 47 17 * * 7
- as: e2e-azure-sdn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_REQUIRES_SSH: yes
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-sdn
  cron: 7 2 * * 6
- as: e2e-ovirt-sdn-upgrade
  steps:
    cluster_profile: ovirt
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-ovirt
  cron: 11 15 * * 7
- as: e2e-vsphere-ovn-upgrade
  steps:
    cluster_profile: vsphere
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-vsphere
  cron: 40 12 * * 7
- as: e2e-vsphere-ovn-upgrade-storage-data
  steps:
    cluster_profile: vsphere
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-vsphere-storage-data
  cron: 42 7 * * 6
- as: e2e-aws-ovn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
  cron: 25 0 * * 7
- as: e2e-gcp-ovn-upgrade
  cluster: build02
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-ovn
  cron: 31 3 * * 7
- as: e2e-gcp-ovn-rt-upgrade
  cluster: build02
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-ovn-rt
  timeout: 5h0m0s
  cron: 1 20 * * 7
- as: e2e-azure-ovn-upgrade
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  cron: 54 18 * * 6
- as: e2e-aws-ovn-uwm
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    pre:
    - ref: ipi-conf-user-workload-monitoring
    - chain: ipi-aws-pre-stableinitial
    workflow: openshift-upgrade-aws
  cron: 11 1 * * 7
- as: e2e-aws-sdn-upgrade-workload
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      EXTERNAL_MANIFESTS_POST_INSTALL: 'true'
      EXTERNAL_MANIFESTS_SHA256_HASH: 6007d0022343793a2c40cc4862337eaf9d5e0f4bd8375578b762ee2a5eb298be
      EXTERNAL_MANIFESTS_URL: 
        https://gist.githubusercontent.com/vrutkovs/1199226040a1942fdbcbe5fa76ab4467/raw/bfc5e67eef6df45f91af76df2a211fb839ebeda9/sample_workload.yaml
    observers:
      enable:
      - observers-resource-watch
    pre:
    - chain: ipi-aws-pre-stableinitial
    - ref: openshift-manifests-external
    workflow: openshift-upgrade-aws
  cron: 11 15 * * 7
- as: e2e-aws-sdn-upgrade-infra
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-infra
  cron: 5 12 * * 7
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.13-upgrade-from-stable-4.12
