releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.3"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.3"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn-multitenant
  cron: 3 3 8,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-gcp
  cron: 57 2 8,15 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws
  cron: 6 8 7,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 55 1 8,23 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.3
