base_images:
  upi-installer:
    name: '4.6'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    release:
      channel: candidate
      version: '4.5'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.6'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 54 9 5,17 * *
  steps:
    cluster_profile: aws
    env:
      LOKI_USE_SERVICEMONITOR: ''
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cron: 56 4 10,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      LOKI_USE_SERVICEMONITOR: ''
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 57 4 5,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      LOKI_USE_SERVICEMONITOR: ''
    workflow: openshift-upgrade-azure
- as: e2e-vsphere-upgrade
  cron: 53 7 9,16 * *
  steps:
    cluster_profile: vsphere
    env:
      LOKI_USE_SERVICEMONITOR: ''
    workflow: openshift-upgrade-vsphere
- as: e2e-ovirt-upgrade
  cron: 33 1 8,22 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-upgrade-ovirt-release-4.4-4.5
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.6-upgrade-from-stable-4.5
