releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.4"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.4"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-gcp-upgrade
  cron: 29 4 9,16 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 54 5 6,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-upgrade-azure
- as: e2e-aws
  cron: 52 9 7,15 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 20 9 9,21 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws-sdn-multitenant
  cron: 31 1 10,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-serial
  cron: 54 2 6,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.4
