base_images:
  ansible:
    name: '4.8'
    namespace: ocp
    tag: ansible
  assisted-test-infra:
    name: ocm-2.9
    namespace: edge-infrastructure
    tag: assisted-test-infra
  aws-ebs-csi-driver-operator-test:
    name: '4.8'
    namespace: ocp
    tag: aws-ebs-csi-driver-operator-test
  azure-disk-csi-driver-operator-test:
    name: '4.8'
    namespace: ocp
    tag: azure-disk-csi-driver-operator-test
  base:
    name: '4.8'
    namespace: ocp
    tag: base
  console-tests:
    name: '4.8'
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  gcp-pd-csi-driver-operator-test:
    name: '4.8'
    namespace: ocp
    tag: gcp-pd-csi-driver-operator-test
  libvirt-installer:
    name: '4.8'
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: '4.8'
    namespace: ocp
    tag: upi-installer
  vsphere-csi-driver-operator-test:
    name: '4.8'
    namespace: ocp
    tag: vsphere-csi-driver-operator-test
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.8'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.8'
  oldest-supported-credentials-request:
    release:
      channel: candidate
      version: 4.8.21
  oldest-supported-z-rollback:
    release:
      channel: candidate
      version: 4.8.22
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-single-node
  cron: 1 2 6,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-single-node
- as: e2e-metal-single-node-live-iso
  cron: 54 3 6,25 * *
  steps:
    cluster_profile: packet-sno
    workflow: baremetalds-sno
- as: e2e-metal-ipi
  cluster: build05
  cron: 26 2 6,19 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ipv4
- as: e2e-metal-ipi-serial-ipv4
  cluster: build05
  cron: 1 9 8,19 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ipv4
- as: e2e-metal-ipi-upgrade
  cluster: build05
  cron: 29 3 9,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade
- as: e2e-metal-ipi-ovn-ipv6
  cluster: build05
  cron: 34 1 7,25 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-ipv6
- as: e2e-metal-ipi-ovn-dualstack
  cluster: build05
  cron: 41 8 9,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-dualstack
- as: e2e-metal-ipi-ovn-dualstack-local-gateway
  cluster: build05
  cron: 34 6 8,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
        OVN_LOCAL_GATEWAY_MODE=true
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-compact
  cluster: build05
  cron: 47 9 7,23 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v6
        NUM_WORKERS=0
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-virtualmedia
  cluster: build05
  cron: 42 3 8,25 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-virtualmedia
- as: e2e-aws-proxy
  cron: 49 3 6,23 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-vsphere
  cron: 21 7 10,15 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
- as: e2e-vsphere-serial
  cron: 21 1 8,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-serial
- as: e2e-vsphere-upi
  cron: 18 2 7,24 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi
- as: e2e-vsphere-upi-serial
  cron: 41 9 7,19 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-serial
- as: e2e-aws-ovn-local-gateway
  cron: 5 7 9,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      GATEWAY_MODE: local
    workflow: openshift-e2e-aws-ovn
- as: e2e-vsphere-ovn
  cron: 5 3 8,22 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-ovn
- as: e2e-vsphere-csi
  cron: 44 7 10,21 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-csi-techpreview
- as: e2e-aws-workers-rhel7
  cron: 23 1 10,18 * *
  steps:
    cluster_profile: aws
    env:
      PLATFORM_VERSION: '7.9'
    workflow: openshift-e2e-aws-workers-rhel
- as: e2e-ovirt
  cron: 9 5 7,23 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-conformance
- as: e2e-ovirt-csi
  cron: 7 4 9,17 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-csi-release-4.8
- as: e2e-gcp-libvirt-cert-rotation
  cron: 23 7 7,20 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-libvirt-cert-rotation
- as: e2e-azure-fips
  cron: 11 4 7,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 13 1 9,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 25 6 7,22 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-fips
  cron: 32 10 10,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp-csi
  cron: 8 5 5,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-csi
- as: e2e-azure-fips-serial
  cron: 36 3 10,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 52 6 8,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 21 5 7,24 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 14 5 9,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-gcp-rt
  cron: 52 9 9,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      RT_ENABLED: 'true'
    workflow: openshift-e2e-gcp-realtime
- as: e2e-aws-upgrade
  cron: 23 2 8,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: credentials-request-freeze
  steps:
    dependencies:
      OPENSHIFT_FROZEN_RELEASE_IMAGE: release:oldest-supported-credentials-request
      OPENSHIFT_LATEST_RELEASE_IMAGE: release:latest
    workflow: openshift-credentials-request-freeze
  cron: 25 7 9,15 * *
- as: e2e-aws-upgrade-rollback-oldest-supported
  cron: 29 4 5,20 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:oldest-supported-z-rollback
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws
  cron: 58 5 7,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 36 3 6,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-csi
  cron: 7 4 8,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi
- as: e2e-aws-csi-migration
  cron: 24 5 8,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi-migration
- as: e2e-azure
  cron: 7 9 8,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-gcp-serial
  cron: 13 7 7,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.8
