base_images:
  console-tests:
    name: "4.3"
    namespace: ocp
    tag: console-tests
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.3"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.3"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: console-aws
  cron: 48 6 7,21 * *
  steps:
    cluster_profile: aws
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 49 3 7,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 40 9 10,15 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 22 10 7,16 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 44 2 10,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 34 5 8,25 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 40 5 7,19 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp
  cron: 57 3 8,25 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws-fips-upgrade
  cron: 24 10 7,19 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-upgrade-aws
- as: e2e-aws
  cron: 22 3 8,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 18 4 8,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 51 6 8,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.3
