base_images:
  upi-installer:
    name: '4.10'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    release:
      channel: candidate
      version: '4.9'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.10'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 4 5 7,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cluster: build02
  cron: 50 8 6,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 35 10 10,18 * *
  steps:
    cluster_profile: azure4
    env:
      TEST_REQUIRES_SSH: 'true'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-ovirt-upgrade
  cron: 24 7 7,22 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-upgrade-ovirt
- as: e2e-vsphere-upgrade
  cron: 34 9 10,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-upgrade-vsphere
- as: e2e-aws-ovn-upgrade
  cron: 31 9 10,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-gcp-ovn-upgrade
  cluster: build02
  cron: 59 2 8,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp-ovn
- as: e2e-gcp-ovn-rt-upgrade
  cluster: build02
  cron: 9 7 8,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      STALLD_ENABLED: 'false'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp-ovn-rt
- as: e2e-azure-ovn-upgrade
  cron: 38 1 7,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-aws-uwm
  cron: 11 3 9,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    pre:
    - ref: ipi-conf-user-workload-monitoring
    - chain: ipi-aws-pre-stableinitial
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-workload
  cron: 25 1 10,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      EXTERNAL_MANIFESTS_POST_INSTALL: 'true'
      EXTERNAL_MANIFESTS_SHA256_HASH: 6007d0022343793a2c40cc4862337eaf9d5e0f4bd8375578b762ee2a5eb298be
      EXTERNAL_MANIFESTS_URL: 
        https://gist.githubusercontent.com/vrutkovs/1199226040a1942fdbcbe5fa76ab4467/raw/bfc5e67eef6df45f91af76df2a211fb839ebeda9/sample_workload.yaml
    pre:
    - chain: ipi-aws-pre-stableinitial
    - ref: openshift-manifests-external
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-infra
  cron: 30 5 6,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws-infra
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.10-upgrade-from-stable-4.9
