releases:
  initial:
    release:
      channel: candidate
      version: '4.4'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.4'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 28 8 9,23 * *
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.4-upgrade-from-stable-4.4
