releases:
  initial:
    prerelease:
      product: okd
      version_bounds:
        lower: 4.13.0-0
        stream: 4-scos-stable
        upper: 4.999.0-0
  latest:
    candidate:
      product: okd
      stream: okd-scos
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
  cron: 19 19 * * 6
- as: e2e-aws-ovn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
  cron: 4 22 * * 6
- as: e2e-gcp-ovn-upgrade
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp
  cron: 28 12 * * 7
- as: e2e-vsphere-ovn
  steps:
    cluster_profile: vsphere-8-vpn
    workflow: openshift-e2e-vsphere
  cron: 44 11 * * 7
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-scos-4.13
