releases:
  initial:
    release:
      channel: candidate
      version: '4.4'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.5'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 15 3 8,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cron: 56 1 5,23 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 59 3 7,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-upgrade-azure
- as: e2e-ovirt-upgrade
  cron: 9 8 6,18 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-upgrade-ovirt-release-4.4-4.5
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.5-upgrade-from-stable-4.4
