releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.7'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.7'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  cron: 45 5 8,22 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-sdn-multitenant
  cron: 33 7 5,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-gcp
  cron: 53 5 5,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-ovn
  cron: 47 4 5,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-ovn
- as: e2e-aws-upgrade-rollback
  cron: 54 7 7,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cron: 47 6 8,20 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 9 1 10,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-upgrade-azure
- as: e2e-aws
  cron: 32 6 5,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 16 7 7,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 31 10 9,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-ovn
  cron: 20 1 5,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-ovn
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.7
