base_images:
  ansible:
    name: '4.7'
    namespace: ocp
    tag: ansible
  base:
    name: '4.7'
    namespace: ocp
    tag: base
  console-tests:
    name: '4.7'
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  libvirt-installer:
    name: '4.7'
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: '4.7'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.7'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.7'
  oldest-supported-credentials-request:
    release:
      channel: candidate
      version: 4.7.38
  oldest-supported-z-rollback:
    release:
      channel: candidate
      version: 4.7.40
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-metal-ipi
  cluster: build05
  cron: 18 9 7,20 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ipv4
- as: e2e-metal-ipi-upgrade
  cluster: build05
  cron: 50 4 9,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
        NETWORK_TYPE=OpenShiftSDN
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade
- as: e2e-metal-ipi-ovn-ipv6
  cluster: build05
  cron: 35 9 5,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v6
        NETWORK_TYPE=OVNKubernetes
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-ovn-dualstack
  cluster: build05
  cron: 37 10 6,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-compact
  cluster: build05
  cron: 44 1 7,23 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v6
        NUM_WORKERS=0
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-virtualmedia
  cluster: build05
  cron: 18 4 6,24 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-virtualmedia
- as: e2e-aws-proxy
  cron: 47 9 9,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-vsphere
  cron: 16 6 10,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
- as: e2e-vsphere-ovn
  cron: 22 8 5,19 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-ovn
- as: e2e-vsphere-serial
  cron: 22 5 7,22 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-serial
- as: e2e-vsphere-upi
  cron: 43 8 7,24 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi
- as: e2e-vsphere-upi-serial
  cron: 33 8 8,22 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-serial
- as: e2e-aws-workers-rhel7
  cron: 49 6 6,20 * *
  steps:
    cluster_profile: aws
    env:
      PLATFORM_VERSION: '7.9'
    workflow: openshift-e2e-aws-workers-rhel
- as: e2e-ovirt
  cron: 3 8 6,19 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-conformance-release-4.6-4.7
- as: e2e-gcp-libvirt-cert-rotation
  cron: 58 8 8,16 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-libvirt-cert-rotation
- as: e2e-azure-fips
  cron: 36 1 9,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 4 4 5,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 25 10 7,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-fips
  cron: 35 4 9,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: 'true'
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 24 3 5,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 28 6 5,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 13 2 10,23 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: 'true'
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 2 4 5,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-gcp-rt
  cron: 37 2 8,20 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      RT_ENABLED: 'true'
    workflow: openshift-e2e-gcp-realtime
- as: e2e-aws-upgrade
  cron: 4 6 5,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: credentials-request-freeze
  steps:
    dependencies:
      OPENSHIFT_FROZEN_RELEASE_IMAGE: release:oldest-supported-credentials-request
      OPENSHIFT_LATEST_RELEASE_IMAGE: release:latest
    workflow: openshift-credentials-request-freeze
  cron: 39 6 9,24 * *
- as: e2e-aws-upgrade-rollback-oldest-supported
  cron: 22 5 10,17 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:oldest-supported-z-rollback
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws
  cron: 38 5 8,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 37 3 7,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 19 9 7,18 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-powervs
  cron: 10 9 7,23 * *
  steps:
    test:
    - as: test-e2e
      cli: latest
      commands: |
        oc get nodes
      from: base
      resources:
        requests:
          cpu: 100m
    workflow: openshift-e2e-powervs-upi
- as: e2e-gcp-serial
  cron: 57 4 6,24 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.7
