releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.2"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.2"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn-multitenant
  cron: 29 2 6,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-gcp
  cron: 8 5 9,23 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws
  cron: 26 1 10,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 14 5 10,25 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.2
