base_images:
  base:
    name: "4.4"
    namespace: ocp
    tag: base
  console-tests:
    name: "4.4"
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  upi-installer:
    name: "4.4"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.4"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.4"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-proxy
  cron: 23 1 8,15 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-aws
  cron: 26 8 8,24 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-upgrade
  cron: 13 1 7,23 * *
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws
- as: e2e-gcp
  cron: 41 1 6,17 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 30 6 7,18 * *
  steps:
    cluster_profile: aws
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-azure-fips
  cron: 23 9 5,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 31 3 5,21 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips
  cron: 51 8 10,21 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-azure-fips-serial
  cron: 13 1 7,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 49 6 8,16 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 4 3 6,22 * *
  steps:
    cluster_profile: gcp
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-aws-fips-upgrade
  cron: 2 6 6,17 * *
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-upgrade-aws
- as: e2e-aws-serial
  cron: 45 4 7,20 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-azure
  cron: 55 2 7,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.4
