releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.2'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.2'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-sdn-multitenant
  cron: 36 9 6,18 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-gcp
  cron: 36 3 5,23 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
- as: e2e-aws
  cron: 24 8 10,17 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 4 7 6,21 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.2
