releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.11"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 9 4 10,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-techpreview
  cron: 38 2 6,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview
- as: e2e-aws-ovn
  cron: 30 7 6,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-serial
  cron: 32 2 8,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-ovn-serial
  cron: 29 10 5,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-techpreview-serial
  cron: 43 3 9,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview-serial
- as: e2e-aws-sdn-multitenant
  cron: 25 9 6,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
- as: e2e-aws-upgrade
  cluster: build01
  cron: 28 10 10,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 1 3 8,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  cron: 43 6 6,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cilium
- as: e2e-aws-imdsv2
  cron: 32 1 5,21 * *
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-azure
  cron: 40 9 9,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-techpreview
  cron: 58 8 8,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview
- as: e2e-azure-serial
  cron: 57 4 10,25 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-serial
- as: e2e-azure-techpreview-serial
  cron: 9 6 6,23 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview-serial
- as: e2e-azure-upgrade
  cron: 35 5 10,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-azure-ovn-upgrade
  cron: 38 6 5,19 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  cron: 2 8 7,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  cron: 14 1 8,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp
  cron: 8 4 9,23 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-techpreview
  cron: 59 9 5,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview
- as: e2e-gcp-ovn
  cron: 9 2 8,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-techpreview-serial
  cron: 43 4 8,23 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview-serial
- as: e2e-gcp-upgrade
  cluster: build02
  cron: 33 5 10,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-gcp-cilium
  cron: 0 7 6,24 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-cilium
- as: e2e-aws-upgrade-rollback
  cron: 35 6 6,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-ovn-single-node
  cron: 57 3 9,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-single-node
- as: e2e-network-migration
  cron: 45 2 7,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-network-migration-rollback
  cron: 37 6 5,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
- as: e2e-aws-cgroupsv2
  cron: 30 6 6,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-crun
  cron: 9 3 9,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.11
