releases:
  latest:
    candidate:
      product: okd
      stream: okd
      version: "4.4"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 21 10 10,18 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.4
