releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: '4.11'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.11'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  cron: 39 9 6,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-techpreview
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview
  cron: 45 3 8,25 * *
- as: e2e-aws-ovn
  cron: 18 10 9,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-serial
  cron: 8 9 10,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-ovn-serial
  cron: 48 9 7,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-techpreview-serial
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-techpreview-serial
  cron: 27 1 6,24 * *
- as: e2e-aws-sdn-multitenant
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-sdn-multi
  cron: 51 5 10,25 * *
- as: e2e-aws-upgrade
  cluster: build01
  cron: 35 7 5,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws-ovn-upgrade
  cluster: build01
  cron: 20 1 8,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cilium
  cron: 46 8 5,24 * *
- as: e2e-aws-imdsv2
  steps:
    cluster_profile: aws-2
    env:
      AWS_METADATA_SERVICE_AUTH: Required
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
  cron: 50 1 9,24 * *
- as: e2e-azure
  cron: 54 2 8,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-techpreview
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview
  cron: 31 5 7,20 * *
- as: e2e-azure-serial
  cron: 20 3 6,17 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-serial
- as: e2e-azure-techpreview-serial
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-techpreview-serial
  cron: 18 4 5,16 * *
- as: e2e-azure-upgrade
  cron: 44 5 10,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-azure-ovn-upgrade
  cron: 26 9 8,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-azure-cilium
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-cilium
  cron: 11 7 8,15 * *
- as: e2e-azure-ovn
  cron: 41 10 10,18 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: 'true'
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp
  cron: 54 4 5,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-techpreview
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview
  cron: 51 5 9,20 * *
- as: e2e-gcp-ovn
  cron: 29 7 8,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: 'true'
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-techpreview-serial
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-techpreview-serial
  cron: 36 4 6,22 * *
- as: e2e-gcp-upgrade
  cluster: build02
  cron: 22 9 6,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-gcp-cilium
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-cilium
  cron: 53 5 5,21 * *
- as: e2e-aws-upgrade-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
  cron: 8 10 5,17 * *
- as: e2e-aws-upgrade-ovn-single-node
  cron: 47 4 10,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-single-node
- as: e2e-network-migration
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
  cron: 7 7 7,23 * *
- as: e2e-network-migration-rollback
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: Alerts shouldn't report any unexpected alerts in firing or pending
        state\| Prometheus \[apigroup:image.openshift.io\] when installed on the cluster
        shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured
    test:
    - ref: ovn-sdn-migration
    - ref: ovn-sdn-migration-rollback
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws
  cron: 53 2 9,17 * *
- as: e2e-aws-cgroupsv2
  cron: 43 2 8,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-crun
  cron: 56 6 9,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-crun
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.11
