base_images:
  upi-installer:
    name: '4.7'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    release:
      channel: candidate
      version: '4.7'
  latest:
    candidate:
      product: ocp
      stream: ci
      version: '4.8'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 38 2 7,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-gcp-upgrade
  cron: 9 10 7,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp
- as: e2e-azure-upgrade
  cron: 9 5 8,22 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure
- as: e2e-ovirt-upgrade
  cron: 34 4 8,15 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-upgrade-ovirt
- as: e2e-vsphere-upgrade
  cron: 10 4 8,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-upgrade-vsphere
- as: e2e-aws-ovn-upgrade
  cron: 39 6 7,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws-ovn
- as: e2e-gcp-ovn-upgrade
  cron: 56 8 8,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-gcp-ovn
- as: e2e-azure-ovn-upgrade
  cron: 3 10 5,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-azure-ovn
- as: e2e-aws-uwm
  cron: 14 1 5,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    pre:
    - ref: ipi-conf-user-workload-monitoring
    - chain: ipi-aws-pre-stableinitial
    workflow: openshift-upgrade-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.8-upgrade-from-stable-4.7
