releases:
  initial:
    candidate:
      product: okd
      stream: okd
      version: '4.12'
  latest:
    candidate:
      product: okd
      stream: okd
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-upgrade
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-upgrade-aws
  cron: 10 19 * * 6
- as: e2e-gcp-ovn-upgrade
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp
  cron: 55 0 * * 7
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: okd-4.13-upgrade-from-okd-4.12
