base_images:
  alibaba-disk-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: alibaba-disk-csi-driver-operator-test
  ansible:
    name: "4.11"
    namespace: ocp
    tag: ansible
  assisted-test-infra:
    name: ocm-2.9
    namespace: edge-infrastructure
    tag: assisted-test-infra
  aws-ebs-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: aws-ebs-csi-driver-operator-test
  azure-disk-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: azure-disk-csi-driver-operator-test
  base:
    name: "4.11"
    namespace: ocp
    tag: base
  cnv-ci-src:
    name: "4.11"
    namespace: cnv
    tag: cnv-ci-src
  cnv-ci-src-upgrade:
    name: "4.11"
    namespace: cnv
    tag: cnv-ci-src-upgrade
  console-tests:
    name: "4.11"
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  driver-toolkit-tests:
    name: "4.11"
    namespace: ocp
    tag: driver-toolkit-tests
  gcp-pd-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: gcp-pd-csi-driver-operator-test
  ibm-vpc-block-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: ibm-vpc-block-csi-driver-operator-test
  libvirt-installer:
    name: "4.11"
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: "4.11"
    namespace: ocp
    tag: upi-installer
  vsphere-csi-driver-operator-test:
    name: "4.11"
    namespace: ocp
    tag: vsphere-csi-driver-operator-test
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.11"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
  oldest-supported-credentials-request:
    release:
      channel: candidate
      version: 4.11.0-fc.0
  oldest-supported-z-rollback:
    release:
      channel: candidate
      version: 4.11.0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-single-node-workers
  cron: 18 7 10,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-single-node-workers
  timeout: 3h0m0s
- as: openshift-e2e-aws-single-node-workers-upgrade-conformance
  cron: 34 6 6,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-single-node-workers-upgrade-conformance
- as: e2e-aws-single-node
  cron: 4 5 5,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-single-node
- as: e2e-aws-single-node-serial
  cron: 5 5 6,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-aws-single-node
- as: e2e-metal-single-node-live-iso
  cron: 14 6 5,21 * *
  steps:
    cluster_profile: packet-sno
    workflow: baremetalds-sno
- as: e2e-metal-single-node-with-worker-live-iso
  cron: 29 8 10,21 * *
  steps:
    cluster_profile: packet-sno
    env:
      PACKET_PLAN: c3.medium.x86
      TEST_FUNC: test_bip_add_worker
    workflow: baremetalds-sno
- as: e2e-metal-ipi-bm
  cluster: build05
  cron: 39 1 7,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      CLUSTERTYPE: baremetal
    workflow: baremetalds-e2e-ipv4
- as: e2e-metal-ipi-ovn-dualstack-local-gateway
  cluster: build05
  cron: 24 4 9,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
        OVN_LOCAL_GATEWAY_MODE=true
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-ovn-ipv4
  cluster: build05
  cron: 11 8 10,19 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-ipv4
- as: e2e-metal-ipi-serial-ipv4
  cluster: build05
  cron: 49 5 9,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ipv4
- as: e2e-metal-ipi-serial-ovn-ipv6
  cluster: build05
  cron: 42 10 9,16 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ovn-ipv6
- as: e2e-metal-ipi-serial-virtualmedia
  cluster: build05
  cron: 59 5 9,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-virtualmedia
- as: e2e-metal-ipi-serial-ovn-dualstack
  cluster: build05
  cron: 34 7 8,25 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ovn-dualstack
- as: e2e-metal-ipi-bm-upgrade
  cluster: build05
  cron: 55 6 5,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      CLUSTERTYPE: baremetal
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade
  timeout: 5h0m0s
- as: e2e-metal-ipi-upgrade-ovn-ipv6
  cluster: build05
  cron: 50 8 7,21 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade-ovn-ipv6
  timeout: 5h0m0s
- as: e2e-metal-ipi-ovn-ipv6
  cluster: build05
  cron: 48 6 9,16 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-ipv6
- as: e2e-metal-ipi-ovn-dualstack
  cluster: build05
  cron: 25 9 10,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-dualstack
- as: e2e-aws-proxy
  cron: 47 8 6,18 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-vsphere
  cron: 29 4 7,25 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
- as: e2e-vsphere-techpreview
  cron: 30 9 6,24 * *
  steps:
    cluster_profile: vsphere
    env:
      TEST_SKIPS: 'In-tree Volumes \[Driver: vsphere\] \[Testpattern: Inline-volume\|
        In-tree Volumes \[Driver: vsphere\] \[Testpattern: Pre-provisioned PV'
    workflow: openshift-e2e-vsphere-techpreview
- as: e2e-aws-ovn-local-gateway
  cron: 40 8 8,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      GATEWAY_MODE: local
    workflow: openshift-e2e-aws-ovn
- as: e2e-vsphere-ovn
  cron: 26 5 6,17 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-ovn
- as: e2e-vsphere-serial
  cron: 50 10 5,18 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-serial
- as: e2e-vsphere-techpreview-serial
  cron: 48 10 6,23 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-techpreview-serial
- as: e2e-vsphere-upi
  cron: 18 10 8,19 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi
- as: e2e-vsphere-upi-serial
  cron: 34 4 6,18 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-serial
- as: e2e-vsphere-csi
  cron: 58 10 9,22 * *
  steps:
    cluster_profile: vsphere
    env:
      TEST_SKIPS: provisioning should mount multiple PV pointing to the same storage
        on the same node
    workflow: openshift-e2e-vsphere-csi
- as: e2e-aws-workers-rhel8
  cron: 53 6 10,25 * *
  steps:
    cluster_profile: aws
    env:
      PLATFORM_VERSION: "8.4"
    workflow: openshift-e2e-aws-workers-rhel
- as: e2e-ovirt
  cron: 44 1 6,17 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-conformance
- as: e2e-ovirt-csi
  cron: 10 6 10,20 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-csi
- as: e2e-ovirt-ovn
  cron: 32 6 8,15 * *
  steps:
    cluster_profile: ovirt
    env:
      NETWORK_TYPE: OVNKubernetes
    workflow: openshift-e2e-ovirt-conformance
- as: e2e-gcp-libvirt-cert-rotation
  cron: 16 3 7,23 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-libvirt-cert-rotation
- as: e2e-azure-fips
  cron: 47 5 6,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 12 5 8,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 39 10 8,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-fips
  cron: 51 5 7,20 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp-csi
  cron: 17 8 8,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-csi
- as: e2e-gcp-csi-migration
  cron: 12 7 9,17 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-csi-migration
- as: e2e-azure-fips-serial
  cron: 25 2 6,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 20 7 9,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 36 3 8,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 4 3 9,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-gcp-rt
  cron: 54 9 6,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      RT_ENABLED: "true"
    workflow: openshift-e2e-gcp-realtime
- as: e2e-aws-upgrade-rollback-oldest-supported
  cron: 28 3 8,23 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:oldest-supported-z-rollback
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: credentials-request-freeze
  cron: 39 6 5,25 * *
  steps:
    dependencies:
      OPENSHIFT_FROZEN_RELEASE_IMAGE: release:oldest-supported-credentials-request
      OPENSHIFT_LATEST_RELEASE_IMAGE: release:latest
    workflow: openshift-credentials-request-freeze
- as: e2e-aws-upgrade
  cron: 26 6 6,19 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws
  cron: 18 4 7,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 20 10 5,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-ovn-serial
  cron: 37 9 6,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-csi
  cron: 48 5 7,25 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi
- as: e2e-aws-csi-migration
  cron: 24 1 9,20 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi-migration
- as: e2e-azure
  cron: 32 8 9,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-csi
  cron: 55 4 6,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-csi
- as: e2e-azurestack-csi
  cron: 27 4 5,22 * *
  steps:
    cluster_profile: azurestack
    env:
      TEST_SKIPS: provisioning should provision storage with pvc data source in parallel
    workflow: openshift-e2e-azurestack-upi-csi
- as: e2e-aws-cgroupsv2
  cron: 25 8 7,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-crun
  cron: 9 1 10,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-crun
- as: e2e-azure-deploy-cnv
  cron: 35 10 6,20 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    test:
    - as: test
      cli: latest
      commands: |
        curl -L https://github.com/openshift-cnv/cnv-ci/tarball/release-4.11 -o /tmp/cnv-ci.tgz
        mkdir -p /tmp/cnv-ci
        tar -xvzf /tmp/cnv-ci.tgz -C /tmp/cnv-ci --strip-components=1
        cd /tmp/cnv-ci
        make deploy_test
      credentials:
      - mount_path: /var/run/cnv-ci-brew-pull-secret
        name: cnv-ci-brew-pull-secret
        namespace: test-credentials
      env:
      - default: '|7820aea2-0d75-11e7-9259-28d244ea5a6d.hhav.f63e13'
        name: BREW_IMAGE_REGISTRY_USERNAME
      - default: /var/run/cnv-ci-brew-pull-secret/token
        name: BREW_IMAGE_REGISTRY_TOKEN_PATH
      - default: v0.53.2
        name: KUBEVIRT_RELEASE
      - default: "4.11"
        name: OCP_VERSION
      - default: /tmp/artifacts
        name: ARTIFACTS_DIR
      - default: openshift-cnv
        name: TARGET_NAMESPACE
      - default: "false"
        name: PRODUCTION_RELEASE
      from: cnv-ci-src
      resources:
        requests:
          cpu: 100m
          memory: 600Mi
    workflow: ipi-azure
- as: e2e-azure-upgrade-cnv
  cron: 15 8 10,25 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    test:
    - as: test
      commands: |
        curl -L https://github.com/openshift-cnv/cnv-ci/tarball/release-4.11 -o /tmp/cnv-ci.tgz
        mkdir -p /tmp/cnv-ci
        tar -xvzf /tmp/cnv-ci.tgz -C /tmp/cnv-ci --strip-components=1
        cd /tmp/cnv-ci
        make upgrade_test
      credentials:
      - mount_path: /var/run/cnv-ci-brew-pull-secret
        name: cnv-ci-brew-pull-secret
        namespace: test-credentials
      env:
      - default: '|7820aea2-0d75-11e7-9259-28d244ea5a6d.hhav.f63e13'
        name: BREW_IMAGE_REGISTRY_USERNAME
      - default: /var/run/cnv-ci-brew-pull-secret/token
        name: BREW_IMAGE_REGISTRY_TOKEN_PATH
      - default: v0.53.2
        name: KUBEVIRT_RELEASE
      - default: "4.11"
        name: OCP_VERSION
      - default: /tmp/artifacts
        name: ARTIFACTS_DIR
      - default: openshift-cnv
        name: TARGET_NAMESPACE
      - default: "false"
        name: PRODUCTION_RELEASE
      from: cnv-ci-src-upgrade
      resources:
        requests:
          cpu: 100m
          memory: 600Mi
    workflow: ipi-azure
- as: e2e-aws-driver-toolkit
  cron: 22 8 8,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: driver-toolkit-tests
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
- as: e2e-telco5g
  cluster: build05
  cron: 46 3 8,20 * *
  steps:
    env:
      E2E_TESTS_CONFIG: |
        CNF_E2E_TESTS=false
        CNF_ORIGIN_TESTS=true
      T5CI_JOB_TYPE: origintests
      T5CI_VERSION: "4.11"
    workflow: telco5g-origin
- as: e2e-telco5g-cnftests
  cluster: build05
  cron: 50 1 8,15 * *
  steps:
    env:
      E2E_TESTS_CONFIG: |
        CNF_E2E_TESTS=true
        CNF_ORIGIN_TESTS=false
      T5CI_JOB_TYPE: cnftests
      T5CI_VERSION: "4.11"
    workflow: telco5g-cnf
- as: e2e-telco5g-ptp
  cluster: build05
  cron: 26 3 5,22 * *
  steps:
    env:
      T5CI_JOB_TYPE: ptp
      T5CI_VERSION: "4.11"
    workflow: telco5g-ptp
- as: e2e-alibaba
  cron: 46 3 10,22 * *
  steps:
    cluster_profile: alibabacloud
    env:
      BASE_DOMAIN: alicloud-dev.devcluster.openshift.com
      TEST_SKIPS: \[StatefulSetBasic\] should not deadlock when a pod.s predecessor
        fails\|\[StatefulSetBasic\] should perform rolling updates and roll backs
        of template modifications with PVCs\|\[StatefulSetBasic\] should provide basic
        identity\|\[StatefulSetBasic\] should adopt matching orphans and release non-matching
        pods\|PVC Protection
    workflow: openshift-e2e-alibabacloud
- as: e2e-alibaba-csi
  cron: 24 5 8,18 * *
  steps:
    cluster_profile: alibabacloud
    env:
      BASE_DOMAIN: alicloud-dev.devcluster.openshift.com
    workflow: openshift-e2e-alibabacloud-disk-csi
- as: e2e-aws-upi
  cron: 46 6 10,18 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-upi
- as: e2e-gcp-serial
  cron: 4 4 7,22 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-serial
- as: e2e-azure-upi
  cron: 5 8 8,24 * *
  steps:
    cluster_profile: azure4
    workflow: openshift-e2e-azure-upi
- as: e2e-gcp-upi
  cron: 6 4 6,15 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-upi
- as: e2e-azurestack-upi
  cron: 50 10 7,22 * *
  steps:
    cluster_profile: azurestack
    workflow: openshift-e2e-azurestack-upi
- as: e2e-ibmcloud-csi
  cron: 49 5 8,16 * *
  steps:
    cluster_profile: ibmcloud
    workflow: openshift-e2e-ibmcloud-csi
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.11
