base_images:
  alibaba-disk-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: alibaba-disk-csi-driver-operator-test
  ansible:
    name: "4.10"
    namespace: ocp
    tag: ansible
  assisted-test-infra:
    name: ocm-2.9
    namespace: edge-infrastructure
    tag: assisted-test-infra
  aws-ebs-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: aws-ebs-csi-driver-operator-test
  azure-disk-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: azure-disk-csi-driver-operator-test
  base:
    name: "4.10"
    namespace: ocp
    tag: base
  cnv-ci-src:
    name: "4.10"
    namespace: cnv
    tag: cnv-ci-src
  cnv-ci-src-upgrade:
    name: "4.10"
    namespace: cnv
    tag: cnv-ci-src-upgrade
  console-tests:
    name: "4.10"
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  driver-toolkit-tests:
    name: "4.10"
    namespace: ocp
    tag: driver-toolkit-tests
  gcp-pd-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: gcp-pd-csi-driver-operator-test
  ibm-vpc-block-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: ibm-vpc-block-csi-driver-operator-test
  libvirt-installer:
    name: "4.10"
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: "4.10"
    namespace: ocp
    tag: upi-installer
  vsphere-csi-driver-operator-test:
    name: "4.10"
    namespace: ocp
    tag: vsphere-csi-driver-operator-test
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.10"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.10"
  oldest-supported-credentials-request:
    release:
      channel: candidate
      version: 4.10.26
  oldest-supported-z-rollback:
    release:
      channel: candidate
      version: 4.10.0-fc.0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-single-node
  cron: 59 8 10,16 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-single-node
- as: e2e-aws-single-node-serial
  cron: 45 5 7,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-aws-single-node
- as: e2e-metal-single-node-live-iso
  cron: 41 5 7,25 * *
  steps:
    cluster_profile: packet-sno
    workflow: baremetalds-sno
- as: e2e-metal-ipi
  cluster: build05
  cron: 34 5 6,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ipv4
- as: e2e-metal-ipi-bm
  cluster: build05
  cron: 53 6 8,17 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      CLUSTERTYPE: baremetal
    workflow: baremetalds-e2e-ipv4
- as: e2e-metal-ipi-ovn-dualstack-local-gateway
  cluster: build05
  cron: 14 6 5,22 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4v6
        NETWORK_TYPE=OVNKubernetes
        OVN_LOCAL_GATEWAY_MODE=true
    workflow: baremetalds-e2e
- as: e2e-metal-ipi-serial-ipv4
  cluster: build05
  cron: 5 3 7,19 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ipv4
- as: e2e-metal-ipi-serial-ovn-ipv6
  cluster: build05
  cron: 35 1 6,19 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ovn-ipv6
- as: e2e-metal-ipi-serial-virtualmedia
  cluster: build05
  cron: 40 1 5,16 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-virtualmedia
- as: e2e-metal-ipi-serial-ovn-dualstack
  cluster: build05
  cron: 21 1 7,24 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-serial-ovn-dualstack
- as: e2e-metal-ipi-bm-upgrade
  cluster: build05
  cron: 37 5 5,15 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      CLUSTERTYPE: baremetal
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade
- as: e2e-metal-ipi-upgrade-ovn-ipv6
  cluster: build05
  cron: 47 5 10,20 * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      TEST_TYPE: upgrade-conformance
    workflow: baremetalds-e2e-upgrade-ovn-ipv6
- as: e2e-metal-ipi-ovn-ipv6
  cluster: build05
  cron: 58 8 9,25 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-ipv6
- as: e2e-metal-ipi-ovn-dualstack
  cluster: build05
  cron: 50 9 8,24 * *
  steps:
    cluster_profile: equinix-ocp-metal
    workflow: baremetalds-e2e-ovn-dualstack
- as: e2e-aws-proxy
  cron: 14 9 8,19 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-proxy
- as: e2e-vsphere
  cron: 1 4 8,21 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere
- as: e2e-vsphere-serial
  cron: 6 7 5,24 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-serial
- as: e2e-vsphere-upi
  cron: 22 6 5,20 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi
- as: e2e-vsphere-upi-serial
  cron: 55 2 6,20 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-upi-serial
- as: e2e-vsphere-techpreview
  cron: 15 7 8,25 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-techpreview
- as: e2e-aws-ovn-local-gateway
  cron: 11 4 7,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      GATEWAY_MODE: local
    workflow: openshift-e2e-aws-ovn
- as: e2e-vsphere-ovn
  cron: 21 4 5,19 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-ovn
- as: e2e-vsphere-techpreview-serial
  cron: 21 5 7,17 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-techpreview-serial
- as: e2e-vsphere-csi
  cron: 18 8 8,21 * *
  steps:
    cluster_profile: vsphere
    workflow: openshift-e2e-vsphere-csi
- as: e2e-aws-workers-rhel8
  cron: 24 6 6,20 * *
  steps:
    cluster_profile: aws
    env:
      PLATFORM_VERSION: "8.4"
    workflow: openshift-e2e-aws-workers-rhel
- as: e2e-ovirt
  cron: 7 8 10,15 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-conformance
- as: e2e-ovirt-ovn
  cron: 31 9 10,16 * *
  steps:
    cluster_profile: ovirt
    env:
      NETWORK_TYPE: OVNKubernetes
    workflow: openshift-e2e-ovirt-conformance
- as: e2e-ovirt-csi
  cron: 29 1 10,25 * *
  steps:
    cluster_profile: ovirt
    workflow: openshift-e2e-ovirt-csi
- as: e2e-gcp-libvirt-cert-rotation
  cron: 31 3 6,20 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-libvirt-cert-rotation
- as: e2e-azure-fips
  cron: 3 10 7,16 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips
  cron: 58 6 8,17 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp
  cron: 54 3 6,18 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp
- as: e2e-gcp-fips
  cron: 9 4 5,16 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: e2e-gcp-csi
  cron: 35 4 7,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-csi
- as: e2e-gcp-csi-migration
  cron: 21 9 5,21 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-csi-migration
- as: e2e-azure-fips-serial
  cron: 58 10 9,15 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-azure-pre
    - ref: fips-check
    workflow: openshift-e2e-azure
- as: e2e-aws-fips-serial
  cron: 18 8 10,21 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-aws-pre
    - ref: fips-check
    workflow: openshift-e2e-aws
- as: e2e-gcp-fips-serial
  cron: 35 2 6,15 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: openshift/conformance/serial
    pre:
    - chain: ipi-gcp-pre
    - ref: fips-check
    workflow: openshift-e2e-gcp
- as: console-aws
  cron: 42 1 10,22 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    test:
    - as: e2e-test
      cli: latest
      commands: ./test-prow-e2e.sh release
      from: console-tests
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: e2e-gcp-rt
  cron: 6 3 10,25 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      RT_ENABLED: "true"
    workflow: openshift-e2e-gcp-realtime
- as: e2e-aws-upgrade
  cron: 16 1 10,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
    workflow: openshift-upgrade-aws
- as: e2e-aws-upgrade-rollback-oldest-supported
  cron: 36 5 5,16 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:oldest-supported-z-rollback
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: abort-at=random
    workflow: openshift-upgrade-aws
- as: credentials-request-freeze
  cron: 11 7 7,21 * *
  steps:
    dependencies:
      OPENSHIFT_FROZEN_RELEASE_IMAGE: release:oldest-supported-credentials-request
      OPENSHIFT_LATEST_RELEASE_IMAGE: release:latest
    workflow: openshift-credentials-request-freeze
- as: e2e-aws
  cron: 31 3 7,15 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws
- as: e2e-aws-serial
  cron: 2 2 9,23 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-serial
- as: e2e-aws-csi
  cron: 45 8 6,24 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi
- as: e2e-aws-csi-migration
  cron: 45 7 5,18 * *
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-csi-migration
- as: e2e-azure
  cron: 5 6 5,24 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure
- as: e2e-azure-csi
  cron: 8 7 10,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-csi
- as: e2e-azure-csi-migration
  cron: 35 1 10,21 * *
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    workflow: openshift-e2e-azure-csi-migration
- as: e2e-azurestack-csi
  cron: 13 5 8,16 * *
  steps:
    cluster_profile: azurestack
    env:
      TEST_SKIPS: provisioning should provision storage with pvc data source in parallel
    workflow: openshift-e2e-azurestack-upi-csi
- as: e2e-aws-cgroupsv2
  cron: 58 3 7,15 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-cgroupsv2
- as: e2e-aws-crun
  cron: 38 5 9,20 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-crun
- as: e2e-azure-deploy-cnv
  cron: 8 1 5,16 * *
  steps:
    cluster_profile: azure4
    test:
    - as: test
      cli: latest
      commands: |
        curl -L https://github.com/openshift-cnv/cnv-ci/tarball/release-4.10 -o /tmp/cnv-ci.tgz
        mkdir -p /tmp/cnv-ci
        tar -xvzf /tmp/cnv-ci.tgz -C /tmp/cnv-ci --strip-components=1
        cd /tmp/cnv-ci
        make deploy_test
      credentials:
      - mount_path: /var/run/cnv-ci-brew-pull-secret
        name: cnv-ci-brew-pull-secret
        namespace: test-credentials
      env:
      - default: '|7820aea2-0d75-11e7-9259-28d244ea5a6d.hhav.f63e13'
        name: BREW_IMAGE_REGISTRY_USERNAME
      - default: /var/run/cnv-ci-brew-pull-secret/token
        name: BREW_IMAGE_REGISTRY_TOKEN_PATH
      - default: v0.45.0
        name: KUBEVIRT_RELEASE
      - default: "4.10"
        name: OCP_VERSION
      - default: /tmp/artifacts
        name: ARTIFACTS_DIR
      - default: openshift-cnv
        name: TARGET_NAMESPACE
      - default: "true"
        name: PRODUCTION_RELEASE
      from: cnv-ci-src
      resources:
        requests:
          cpu: 100m
          memory: 600Mi
    workflow: ipi-azure
- as: e2e-azure-upgrade-cnv
  cron: 3 3 9,25 * *
  steps:
    cluster_profile: azure4
    test:
    - as: test
      commands: |
        curl -L https://github.com/openshift-cnv/cnv-ci/tarball/release-4.10 -o /tmp/cnv-ci.tgz
        mkdir -p /tmp/cnv-ci
        tar -xvzf /tmp/cnv-ci.tgz -C /tmp/cnv-ci --strip-components=1
        cd /tmp/cnv-ci
        make upgrade_test
      credentials:
      - mount_path: /var/run/cnv-ci-brew-pull-secret
        name: cnv-ci-brew-pull-secret
        namespace: test-credentials
      env:
      - default: '|7820aea2-0d75-11e7-9259-28d244ea5a6d.hhav.f63e13'
        name: BREW_IMAGE_REGISTRY_USERNAME
      - default: /var/run/cnv-ci-brew-pull-secret/token
        name: BREW_IMAGE_REGISTRY_TOKEN_PATH
      - default: v0.45.0
        name: KUBEVIRT_RELEASE
      - default: "4.10"
        name: OCP_VERSION
      - default: /tmp/artifacts
        name: ARTIFACTS_DIR
      - default: openshift-cnv
        name: TARGET_NAMESPACE
      - default: "true"
        name: PRODUCTION_RELEASE
      from: cnv-ci-src-upgrade
      resources:
        requests:
          cpu: 100m
          memory: 600Mi
    workflow: ipi-azure
- as: e2e-aws-driver-toolkit
  cron: 1 1 6,15 * *
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: driver-toolkit-tests
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
- as: e2e-alibaba
  cron: 44 2 5,21 * *
  steps:
    cluster_profile: alibabacloud
    env:
      BASE_DOMAIN: alicloud-dev.devcluster.openshift.com
      TEST_SKIPS: \[StatefulSetBasic\] should not deadlock when a pod.s predecessor
        fails\|\[StatefulSetBasic\] should perform rolling updates and roll backs
        of template modifications with PVCs\|\[StatefulSetBasic\] should provide basic
        identity\|\[StatefulSetBasic\] should adopt matching orphans and release non-matching
        pods\|PVC Protection
    workflow: openshift-e2e-alibabacloud
- as: e2e-gcp-serial
  cron: 22 9 10,19 * *
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    workflow: openshift-e2e-gcp-serial
- as: e2e-alibaba-csi
  cron: 41 5 9,19 * *
  steps:
    cluster_profile: alibabacloud
    env:
      BASE_DOMAIN: alicloud-dev.devcluster.openshift.com
    workflow: openshift-e2e-alibabacloud-disk-csi
- as: e2e-aws-upi
  cron: 37 5 5,18 * *
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-upi
- as: e2e-azure-upi
  cron: 40 10 6,22 * *
  steps:
    cluster_profile: azure4
    workflow: openshift-e2e-azure-upi
- as: e2e-azurestack-upi
  cron: 36 4 5,23 * *
  steps:
    cluster_profile: azurestack
    workflow: openshift-e2e-azurestack-upi
- as: e2e-gcp-upi
  cron: 18 3 9,23 * *
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp-upi
- as: e2e-ibmcloud-csi
  cron: 3 1 8,25 * *
  steps:
    cluster_profile: ibmcloud
    env:
      TEST_SKIPS: Verify if offline PVC expansion works\| topology should provision
        a volume and schedule a pod with AllowedTopologies
    workflow: openshift-e2e-ibmcloud-csi
- as: e2e-telco5g-ptp
  cluster: build05
  cron: 14 6 6,20 * *
  steps:
    env:
      T5CI_JOB_TYPE: ptp
      T5CI_VERSION: "4.10"
    workflow: telco5g-ptp
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: nightly-4.10
