base_images:
  ansible:
    name: '4.13'
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: '4.13'
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: '4.13'
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: '4.13'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.13'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-debug
  cron: 4 10 * * 6
  steps:
    cluster_profile: vsphere-8-vpn
    env:
      SLEEP_DURATION: 2h
    post:
    - ref: cucushift-installer-wait
    - chain: cucushift-installer-rehearse-vsphere-ipi-deprovision
    pre:
    - chain: cucushift-installer-rehearse-vsphere-ipi-ovn-etcd-encryption-provision
- as: installer-rehearse-aws
  cron: 44 19 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-aws-ipi-compact
- as: installer-rehearse-azure
  cron: 44 17 * * 6
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: installer-rehearse-azure-aro
  cron: 14 7 * * 7
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: 4.11.26
    workflow: cucushift-installer-rehearse-azure-aro
- as: installer-rehearse-azure-stack
  cluster: build01
  cron: 3 15 * * 7
  steps:
    cluster_profile: azurestack-qe
    workflow: cucushift-installer-rehearse-azure-stack-upi
- as: installer-rehearse-alibabacloud
  cron: 3 20 * * 6
  steps:
    cluster_profile: alibabacloud-qe
    workflow: cucushift-installer-rehearse-alibabacloud-ipi-private
- as: installer-rehearse-ibmcloud
  cron: 22 4 * * 6
  steps:
    cluster_profile: ibmcloud-qe
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-workers-rhel8
- as: installer-rehearse-gcp
  cron: 57 3 * * 7
  steps:
    cluster_profile: gcp-qe
    workflow: cucushift-installer-rehearse-gcp-ipi-sno
- as: installer-rehearse-vsphere-8
  cron: 4 20 * * 7
  steps:
    cluster_profile: vsphere-8-vpn
    workflow: cucushift-installer-rehearse-vsphere-upi
- as: installer-rehearse-vsphere-multizone
  cron: 14 23 * * 7
  steps:
    cluster_profile: vsphere-multizone
    workflow: cucushift-installer-rehearse-vsphere-ipi-zones
- as: installer-rehearse-nutanix-dis
  cluster: build01
  cron: 39 13 * * 6
  steps:
    cluster_profile: nutanix-qe-dis
    workflow: cucushift-installer-rehearse-nutanix-ipi-proxy
- as: installer-rehearse-vsphere-connected
  cron: 35 21 * * 6
  steps:
    cluster_profile: vsphere-connected
    workflow: cucushift-installer-rehearse-vsphere-ipi-remote-worker
- as: installer-rehearse-vsphere
  cron: 18 18 * * 7
  steps:
    cluster_profile: vsphere
    workflow: cucushift-installer-rehearse-vsphere-ipi-ovn-dualstack
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.13
