base_images:
  ansible:
    name: '4.10'
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: '4.10'
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: '4.10'
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: '4.10'
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.10'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.10'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-debug
  cron: 15 4 8,19 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      SLEEP_DURATION: 2h
    post:
    - ref: cucushift-installer-wait
    - chain: cucushift-installer-rehearse-aws-ipi-deprovision
    pre:
    - chain: cucushift-installer-rehearse-aws-ipi-provision
- as: installer-rehearse-aws
  cron: 34 7 9,20 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-workers-rhcos-rhel8
- as: installer-rehearse-aws-usgov
  cron: 29 2 5,25 * *
  steps:
    cluster_profile: aws-usgov-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: 
      cucushift-installer-rehearse-aws-usgov-ipi-private-cco-manual-security-token-service
- as: installer-rehearse-azure
  cron: 14 2 10,19 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-ipi-private-ovn
- as: installer-rehearse-azure-mag
  cron: 41 5 8,22 * *
  steps:
    cluster_profile: azuremag-qe
    env:
      BASE_DOMAIN: qemag.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-mag-ipi
- as: installer-rehearse-azure-aro
  cron: 16 1 9,17 * *
  steps:
    cluster_profile: azure-qe
    env:
      ARO_WORKER_COUNT: '4'
      ARO_WORKER_VM_SIZE: Standard_D8s_v3
    workflow: cucushift-installer-rehearse-azure-aro
- as: installer-rehearse-alibabacloud
  cron: 42 7 8,23 * *
  steps:
    cluster_profile: alibabacloud-qe
    workflow: cucushift-installer-rehearse-alibabacloud-ipi
- as: installer-rehearse-gcp
  cron: 38 10 6,16 * *
  steps:
    cluster_profile: gcp-qe
    workflow: cucushift-installer-rehearse-gcp-ipi
- as: installer-rehearse-vsphere
  cron: 59 9 7,24 * *
  steps:
    cluster_profile: vsphere
    workflow: 
      cucushift-installer-rehearse-vsphere-ipi-ovn-local-to-shared-gateway-mode-migration
- as: installer-rehearse-vsphere-dis
  cron: 19 1 7,16 * *
  steps:
    cluster_profile: vsphere-dis
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-techpreview
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.10
