base_images:
  ansible:
    name: "4.10"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.10"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.10"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.10"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.10"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.10"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-debug
  cron: 48 5 10,21 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      SLEEP_DURATION: 2h
    post:
    - ref: cucushift-installer-wait
    - chain: cucushift-installer-rehearse-aws-ipi-deprovision
    pre:
    - chain: cucushift-installer-rehearse-aws-ipi-provision
- as: installer-rehearse-aws
  cron: 27 7 10,25 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-workers-rhcos-rhel8
- as: installer-rehearse-aws-usgov
  cron: 43 1 9,19 * *
  steps:
    cluster_profile: aws-usgov-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-aws-usgov-ipi-private-cco-manual-security-token-service
- as: installer-rehearse-azure
  cron: 23 8 5,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-ipi-private-ovn
- as: installer-rehearse-azure-mag
  cron: 32 3 10,25 * *
  steps:
    cluster_profile: azuremag-qe
    env:
      BASE_DOMAIN: qemag.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-mag-ipi
- as: installer-rehearse-azure-aro
  cron: 5 4 8,16 * *
  steps:
    cluster_profile: azure-qe
    env:
      ARO_WORKER_COUNT: "4"
      ARO_WORKER_VM_SIZE: Standard_D8s_v3
    workflow: cucushift-installer-rehearse-azure-aro
- as: installer-rehearse-alibabacloud
  cron: 53 2 5,20 * *
  steps:
    cluster_profile: alibabacloud-qe
    workflow: cucushift-installer-rehearse-alibabacloud-ipi
- as: installer-rehearse-gcp
  cron: 6 7 9,18 * *
  steps:
    cluster_profile: gcp-qe
    workflow: cucushift-installer-rehearse-gcp-ipi
- as: installer-rehearse-vsphere
  cron: 15 8 6,19 * *
  steps:
    cluster_profile: vsphere
    workflow: cucushift-installer-rehearse-vsphere-ipi-ovn-local-to-shared-gateway-mode-migration
- as: installer-rehearse-vsphere-dis
  cron: 59 7 9,25 * *
  steps:
    cluster_profile: vsphere-dis
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-techpreview
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.10
