base_images:
  ansible:
    name: '4.9'
    namespace: ocp
    tag: ansible
  cli:
    name: '4.9'
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: '4.9'
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: '4.10'
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: '4.9'
  tools:
    name: '4.9'
    namespace: ocp
    tag: tools
  upi-installer:
    name: '4.9'
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.9.0
        upper: 4.10.0-0
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: '4.10'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aws-c2s-ipi-disconnected-private-fips-f360
  cron: 56 10 8,25 * *
  steps:
    cluster_profile: aws-c2s-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private
- as: aws-ipi-byo-iam-role-f360
  cron: 47 3 7,19 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-iam-role
- as: aws-ipi-byo-kms-etcd-encryption-f360
  cron: 5 4 6,21 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-kms-etcd-encryption
- as: aws-ipi-byo-route53-f360
  cron: 14 2 8,24 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-route53
- as: aws-ipi-disconnected-private-f360
  cron: 9 9 6,24 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private
- as: aws-ipi-ovn-fips-f360
  cron: 16 3 5,18 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-ovn
- as: aws-ipi-ovn-ingress-nlb-f360
  cron: 27 9 8,18 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips
        and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips
        and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ingress-nlb
- as: aws-ipi-ovn-ipsec-f360
  cron: 43 9 8,15 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips
        and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips
        and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ipsec
- as: aws-ipi-private-f360
  cron: 19 5 10,22 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-private
- as: aws-ipi-proxy-workers-rhel8-f360
  cron: 46 2 5,20 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      PLATFORM_VERSION: '8.6'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-workers-rhel8
- as: aws-upi-f360
  cron: 40 3 8,23 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-upi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-upi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-upi
- as: aws-usgov-ipi-private-f360
  cron: 11 5 10,16 * *
  steps:
    cluster_profile: aws-usgov-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @aws-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @aws-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-usgov-ipi-private
- as: azure-ipi-disconnected-fullyprivate-f360
  cron: 4 5 10,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and @disconnected
        and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and @disconnected
        and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate
- as: azure-ipi-fips-f360
  cron: 38 1 8,18 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi
- as: azure-ipi-fullyprivate-proxy-f360
  cron: 19 1 9,19 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: azure-ipi-ovn-ipsec-f360
  cron: 49 10 7,19 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips
        and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips
        and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-ovn-ipsec
- as: azure-ipi-private-f360
  cron: 56 1 7,15 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-private
- as: azure-ipi-proxy-workers-rhcos-rhel8-f360
  cron: 18 2 10,21 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      PLATFORM_VERSION: '8.6'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-proxy-workers-rhcos-rhel8
- as: azure-ipi-resourcegroup-f360
  cron: 53 10 7,18 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-resourcegroup
- as: azure-ipi-workers-rhel8-f360
  cron: 59 9 6,24 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      PLATFORM_VERSION: '8.6'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-workers-rhel8
- as: azure-upi-f360
  cron: 28 2 7,17 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @azure-upi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @azure-upi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-upi
- as: gcp-ipi-disconnected-private-rt-f360
  cron: 57 1 5,25 * *
  steps:
    cluster_profile: gcp-qe
    env:
      RT_ENABLED: 'true'
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @gcp-ipi and @disconnected
        and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @gcp-ipi and @disconnected
        and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-gcp-ipi-disconnected-private
- as: gcp-ipi-ovn-ipsec-f360
  cron: 19 6 9,15 * *
  steps:
    cluster_profile: gcp-qe
    env:
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @gcp-ipi and not @fips
        and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @gcp-ipi and not @fips
        and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-gcp-ipi-ovn-ipsec
- as: gcp-ipi-proxy-private-f360
  cron: 30 2 10,22 * *
  steps:
    cluster_profile: gcp-qe
    env:
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @gcp-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @gcp-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-gcp-ipi-proxy-private
- as: gcp-ipi-workers-rhel8-f360
  cron: 12 10 6,21 * *
  steps:
    cluster_profile: gcp-qe
    env:
      PLATFORM_VERSION: '8.6'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @gcp-ipi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @gcp-ipi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-gcp-ipi-workers-rhel8
- as: gcp-upi-f360
  cron: 33 5 10,25 * *
  steps:
    cluster_profile: gcp-qe
    env:
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @gcp-upi and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @gcp-upi and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-gcp-upi
- as: vsphere-ipi-disconnected-registry-pvc-f360
  cron: 31 9 7,22 * *
  steps:
    cluster_profile: vsphere-dis
    env:
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @vsphere-ipi and @disconnected
        and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @vsphere-ipi and @disconnected
        and not @fips'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-image-registry-pvc
- as: vsphere-ipi-ovn-ipsec-f360
  cron: 5 4 8,22 * *
  steps:
    cluster_profile: vsphere
    env:
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @vsphere-ipi and not @fips
        and @network-ovnkubernetes'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @vsphere-ipi and not @fips
        and @network-ovnkubernetes'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-vsphere-ipi-ovn-ipsec
- as: vsphere-ipi-proxy-fips-f360
  cron: 27 7 5,20 * *
  steps:
    cluster_profile: vsphere-dis
    env:
      FIPS_ENABLED: 'true'
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @vsphere-ipi and @proxy'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @vsphere-ipi and @proxy'
    test:
    - ref: cucushift-installer-check
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-vsphere-ipi-proxy
- as: vsphere-upi-disconnected-secureboot-f360
  cron: 14 7 7,16 * *
  steps:
    cluster_profile: vsphere-dis
    env:
      TEST_FILTERS: ~ConnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.9 and @vsphere-upi and @disconnected
        and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.9 and @vsphere-upi and @disconnected
        and not @fips'
    test:
    - ref: cucushift-installer-check
    - ref: cucushift-upgrade-vsphere-hw
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-vsphere-upi-disconnected-secureboot
zz_generated_metadata:
  branch: release-4.10
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-4.10-upgrade-from-stable-4.9
