base_images:
  ansible:
    name: '4.13'
    namespace: ocp
    tag: ansible
  cli:
    name: '4.13'
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: '4.13'
    namespace: ocp
    tag: openstack-installer
  tests-private:
    name: tests-private
    namespace: ci
    tag: '4.13'
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: '4.13'
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: '4.13'
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: '4.13'
  tools:
    name: '4.13'
    namespace: ocp
    tag: tools
  upi-installer:
    name: '4.13'
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: '4.13'
  target:
    release:
      architecture: multi
      channel: candidate
      version: '4.13'
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 4Gi
tests:
- as: aws-c2s-ipi-disconnected-private-fips-f14
  cron: 10 19 * * 7
  steps:
    cluster_profile: aws-c2s-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private
- as: aws-ipi-disconnected-mtu-localzone-fips-f14
  cron: 6 11 * * 7
  steps:
    cluster_profile: aws-1-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone
- as: aws-ipi-disconnected-private-sno-f14
  cron: 45 15 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-sno
- as: aws-ipi-disconnected-sts-ep-fips-f14
  cron: 52 13 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: 
      cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-private-s3-with-ep-sts-ec2-elb
- as: aws-ipi-ovn-ipsec-to-multiarch-f14
  cron: 39 3 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.13 and @aws-ipi and @heterogeneous
        and @network-ovnkubernetes and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.13 and @aws-ipi and @heterogeneous
        and @network-ovnkubernetes and not @fips'
    test:
    - chain: openshift-upgrade-qe-test-arch-migration
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ipsec
- as: aws-ipi-proxy-sts-f14
  cron: 25 11 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-cco-manual-security-token-service
- as: aws-ipi-shared-vpc-phz-sts-fips-f14
  cron: 20 8 * * 6
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-shared-vpc-phz-sts
- as: aws-ipi-usertags-fips-f14
  cron: 50 2 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-usertags
- as: aws-ocm-osd-ccs-f7
  cron: 29 19 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      CHANNEL_GROUP: candidate
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @osd_ccs and @network-ovnkubernetes and
        not @fips'
      EC_BUILD: 'true'
      OPENSHIFT_VERSION: '4.13'
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;OSD_CCS&
    test:
    - chain: openshift-e2e-test-qe
    workflow: osd-ccs-aws
- as: aws-rosa-sts-f7
  cron: 18 21 * * 7
  steps:
    cluster_profile: aws-qe
    env:
      CHANNEL_GROUP: candidate
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        not @fips'
      OPENSHIFT_VERSION: '4.13'
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;ROSA&
    test:
    - chain: openshift-e2e-test-qe
    workflow: rosa-aws-sts
- as: aws-rosa-sts-hypershift-guest-integration-critical-f2
  cron: 11 22 * * 6
  steps:
    cluster_profile: aws-sd-qe
    env:
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        @hypershift-hosted and @critical and not @fips'
      OCM_LOGIN_ENV: integration
      OPENSHIFT_VERSION: '4.13'
      ROSA_LOGIN_ENV: integration
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;~NonHyperShiftHOST&;ROSA&
      TEST_IMPORTANCE: Critical
    test:
    - chain: openshift-e2e-test-hypershift-qe
    workflow: rosa-aws-sts-hypershift
- as: aws-rosa-sts-hypershift-guest-integration-full-f7
  cron: 34 20 * * 6
  steps:
    cluster_profile: aws-sd-qe
    env:
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        @hypershift-hosted and not @fips'
      OCM_LOGIN_ENV: integration
      OPENSHIFT_VERSION: '4.13'
      ROSA_LOGIN_ENV: integration
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;~NonHyperShiftHOST&;ROSA&
    test:
    - chain: openshift-e2e-test-hypershift-qe
    workflow: rosa-aws-sts-hypershift
- as: aws-rosa-sts-hypershift-guest-stage-critical-f2
  cron: 27 12 * * 6
  steps:
    cluster_profile: aws-sd-qe
    env:
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        @hypershift-hosted and @critical and not @fips'
      OPENSHIFT_VERSION: '4.13'
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;~NonHyperShiftHOST&;ROSA&
      TEST_IMPORTANCE: Critical
    test:
    - chain: openshift-e2e-test-hypershift-qe
    workflow: rosa-aws-sts-hypershift
- as: aws-rosa-sts-hypershift-guest-stage-full-f7
  cron: 50 13 * * 6
  steps:
    cluster_profile: aws-sd-qe
    env:
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        @hypershift-hosted and not @fips'
      OPENSHIFT_VERSION: '4.13'
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;~NonHyperShiftHOST&;ROSA&
    test:
    - chain: openshift-e2e-test-hypershift-qe
    workflow: rosa-aws-sts-hypershift
- as: aws-rosa-sts-hypershift-sector-guest-prod-critical-f2
  cron: 47 2 * * 6
  steps:
    cluster_profile: aws-sd-qe
    env:
      CLUSTER_SECTOR: canary
      E2E_RUN_TAGS: '@amd64 and @aws-ipi and @rosa and @network-ovnkubernetes and
        @hypershift-hosted and @critical and not @fips'
      OCM_LOGIN_ENV: production
      OPENSHIFT_VERSION: '4.13'
      REGION: us-east-1
      ROSA_LOGIN_ENV: production
      TAG_VERSION: '@4.13'
      TEST_FILTERS: 
        ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&;~HyperShiftMGMT&;~MicroShiftOnly&;~NonHyperShiftHOST&;ROSA&
      TEST_IMPORTANCE: Critical
    test:
    - chain: openshift-e2e-test-hypershift-qe
    workflow: rosa-aws-sts-hypershift-sector
- as: aws-usgov-ipi-private-sts-f14
  cron: 41 21 * * 6
  steps:
    cluster_profile: aws-usgov-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: 
      cucushift-installer-rehearse-aws-usgov-ipi-private-cco-manual-security-token-service
- as: azure-ipi-disconnected-fullyprivate-f14
  cron: 43 15 * * 6
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate
- as: azure-ipi-fullyprivate-proxy-f14
  cron: 2 23 * * 6
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: azure-ipi-to-multiarch-f14
  cron: 3 22 * * 6
  steps:
    cluster_profile: azure-qe
    env:
      ADDITIONAL_WORKER_VM_TYPE: Standard_D4ps_v5
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      UPGRADE_CHECK_RUN_TAGS: '@upgrade-check and @4.13 and @azure-ipi and @heterogeneous
        and @network-ovnkubernetes and not @fips'
      UPGRADE_PRE_RUN_TAGS: '@upgrade-prepare and @4.13 and @azure-ipi and @heterogeneous
        and @network-ovnkubernetes and not @fips'
    test:
    - chain: openshift-upgrade-qe-test-arch-migration
    workflow: cucushift-installer-rehearse-azure-ipi
- as: azure-mag-ipi-fips-f14
  cron: 13 8 * * 6
  steps:
    cluster_profile: azuremag-qe
    env:
      BASE_DOMAIN: qemag.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-mag-ipi
- as: azure-stack-ipi-proxy-fips-f14
  cluster: build01
  cron: 25 21 * * 7
  steps:
    cluster_profile: azurestack-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-stack-ipi-proxy
- as: gcp-ipi-compact-filestore-csi-f14
  cron: 38 13 * * 6
  steps:
    cluster_profile: gcp-qe
    dependency_overrides:
      OO_INDEX: quay.io/openshift-qe-optional-operators/aosqe-index:v4.13
    env:
      SIZE_VARIANT: compact
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-filestore-csi
- as: gcp-ipi-disconnected-private-workload-identity-f14
  cron: 51 7 * * 7
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: 
      cucushift-installer-rehearse-gcp-ipi-disconnected-private-cco-manual-workload-identity
- as: gcp-ipi-proxy-private-f14
  cron: 31 10 * * 7
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-proxy-private
- as: gcp-ipi-xpn-fips-f14
  cron: 25 14 * * 6
  steps:
    cluster_profile: gcp-qe
    env:
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-xpn
- as: ibmcloud-ipi-private-fips-f14
  cron: 45 6 * * 7
  steps:
    cluster_profile: ibmcloud-qe
    env:
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-private
- as: nutanix-ipi-disconnected-f14
  cluster: build01
  cron: 14 15 * * 6
  steps:
    cluster_profile: nutanix-qe-dis
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-nutanix-ipi-disconnected
- as: nutanix-ipi-proxy-fips-f14
  cluster: build01
  cron: 56 5 * * 6
  steps:
    cluster_profile: nutanix-qe-dis
    env:
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-nutanix-ipi-proxy
- as: vsphere-ipi-disconnected-registry-pvc-f14
  cron: 31 8 * * 7
  steps:
    cluster_profile: vsphere-dis
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-image-registry-pvc
- as: vsphere-ipi-ovn-dualstack-f14
  cron: 17 10 * * 7
  steps:
    cluster_profile: vsphere
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-ovn-dualstack
- as: vsphere-ipi-proxy-fips-f14
  cron: 18 2 * * 7
  steps:
    cluster_profile: vsphere-dis
    env:
      FIPS_ENABLED: 'true'
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-proxy
- as: vsphere-ipi-zones-f14
  cron: 31 18 * * 7
  steps:
    cluster_profile: vsphere-multizone
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-zones
zz_generated_metadata:
  branch: release-4.13
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable
