base_images:
  ansible:
    name: "4.11"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.11"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.11"
  tools:
    name: "4.11"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.11"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.11"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: aws-c2s-ipi-disconnected-private-fips-f28
  cron: 22 2 9,15 * *
  steps:
    cluster_profile: aws-c2s-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private
- as: aws-ipi-disconnected-sts-ep-fips-f28
  cron: 11 2 7,18 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-private-s3-with-ep-sts-ec2-elb
- as: aws-ipi-ovn-fips-f28
  cron: 21 10 10,23 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-ovn
- as: aws-ipi-proxy-sts-f28
  cron: 52 2 5,18 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-cco-manual-security-token-service
- as: azure-ipi-disconnected-fullyprivate-f28
  cron: 12 9 9,16 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate
- as: azure-ipi-fips-f28
  cron: 33 7 6,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi
- as: azure-ipi-fullyprivate-proxy-f28
  cron: 21 4 5,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: gcp-ipi-disconnected-private-workload-identity-f28
  cron: 1 4 10,15 * *
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-disconnected-private-cco-manual-workload-identity
- as: gcp-ipi-proxy-private-f28
  cron: 49 7 10,21 * *
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-proxy-private
- as: vsphere-ipi-disconnected-registry-pvc-f28
  cron: 23 8 8,17 * *
  steps:
    cluster_profile: vsphere-dis
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-image-registry-pvc
- as: vsphere-ipi-proxy-fips-f28
  cron: 13 9 9,15 * *
  steps:
    cluster_profile: vsphere-dis
    env:
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-proxy
zz_generated_metadata:
  branch: release-4.11
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable
