base_images:
  ansible:
    name: "4.10"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.10"
    namespace: ocp
    tag: cli
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.10"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.10"
  tools:
    name: "4.10"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.10"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.10"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: aws-c2s-ipi-disconnected-private-fips-f360
  cron: 51 4 9,15 * *
  steps:
    cluster_profile: aws-c2s-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private
- as: aws-ipi-disconnected-sts-ep-fips-f360
  cron: 57 7 7,16 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-private-s3-with-ep-sts-ec2-elb
- as: aws-ipi-ovn-fips-f360
  cron: 50 3 9,18 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-ovn
- as: aws-ipi-proxy-sts-f360
  cron: 55 1 7,22 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-cco-manual-security-token-service
- as: azure-ipi-disconnected-fullyprivate-f360
  cron: 22 3 8,15 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate
- as: azure-ipi-fips-f360
  cron: 44 8 5,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi
- as: azure-ipi-fullyprivate-proxy-f360
  cron: 52 8 5,22 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: gcp-ipi-disconnected-private-workload-identity-f360
  cron: 24 3 5,20 * *
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-disconnected-private-cco-manual-workload-identity
- as: gcp-ipi-proxy-private-f360
  cron: 3 8 9,17 * *
  steps:
    cluster_profile: gcp-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-gcp-ipi-proxy-private
- as: vsphere-ipi-disconnected-registry-pvc-f360
  cron: 59 7 5,21 * *
  steps:
    cluster_profile: vsphere-dis
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected-image-registry-pvc
- as: vsphere-ipi-proxy-fips-f360
  cron: 17 9 5,19 * *
  steps:
    cluster_profile: vsphere-dis
    env:
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-proxy
zz_generated_metadata:
  branch: release-4.10
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable
