base_images:
  ansible:
    name: '4.11'
    namespace: ocp
    tag: ansible
  assisted-installer:
    name: assisted
    namespace: ocp-kni
    tag: assisted-installer
  assisted-installer-agent:
    name: assisted
    namespace: ocp-kni
    tag: assisted-installer-agent
  assisted-installer-controller:
    name: assisted
    namespace: ocp-kni
    tag: assisted-installer-controller
  assisted-service:
    name: assisted
    namespace: ocp-kni
    tag: assisted-service
  assisted-test-infra:
    name: assisted-test
    namespace: ocp-kni
    tag: assisted-test-infra
  aws-ebs-csi-driver-operator-test:
    name: '4.11'
    namespace: ocp
    tag: aws-ebs-csi-driver-operator-test
  azure-disk-csi-driver-operator-test:
    name: '4.11'
    namespace: ocp
    tag: azure-disk-csi-driver-operator-test
  base:
    name: '4.11'
    namespace: ocp
    tag: base
  console-tests:
    name: '4.11'
    namespace: ocp
    tag: console-tests
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  gcp-pd-csi-driver-operator-test:
    name: '4.11'
    namespace: ocp
    tag: gcp-pd-csi-driver-operator-test
  libvirt-installer:
    name: '4.11'
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: '4.11'
    namespace: ocp
    tag: upi-installer
  vsphere-csi-driver-operator-test:
    name: '4.11'
    namespace: ocp
    tag: vsphere-csi-driver-operator-test
releases:
  arm64-initial:
    candidate:
      architecture: arm64
      product: ocp
      relative: 1
      stream: nightly
      version: '4.11'
  arm64-latest:
    candidate:
      architecture: arm64
      product: ocp
      stream: nightly
      version: '4.11'
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: '4.11'
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.11'
  multi-initial:
    candidate:
      architecture: multi
      product: ocp
      relative: 1
      stream: nightly
      version: '4.11'
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: '4.11'
  ppc64le-initial:
    candidate:
      architecture: ppc64le
      product: ocp
      relative: 1
      stream: nightly
      version: '4.11'
  ppc64le-latest:
    candidate:
      architecture: ppc64le
      product: ocp
      stream: nightly
      version: '4.11'
  s390x-initial:
    candidate:
      architecture: s390x
      product: ocp
      relative: 1
      stream: nightly
      version: '4.11'
  s390x-latest:
    candidate:
      architecture: s390x
      product: ocp
      stream: nightly
      version: '4.11'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ocp-e2e-aws-ovn-heterogeneous-upgrade
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:multi-initial
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:multi-latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-upgrade-aws-heterogeneous
  cron: 7 1 7,19 * *
- as: ocp-e2e-aws-heterogeneous
  cron: 10 10 8,19 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:multi-latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    workflow: openshift-e2e-aws-heterogeneous
- as: ocp-e2e-serial-aws-heterogeneous
  cron: 49 4 7,21 * *
  steps:
    cluster_profile: aws-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:multi-latest
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
      TEST_SKIPS: EgressIPs can be assigned automatically\| OpenShift alerting rules\|
        pods should have the assigned EgressIPs\| only pods matched by the pod selector
        should have the EgressIPs\| Image signature workflow can push a signed image
        to openshift registry and verify it\| Multi-AZ Clusters should spread the
        pods of a service across zones\| pods should keep the assigned EgressIPs
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-aws-heterogeneous
- as: ocp-e2e-aws-arm64
  cron: 23 7 7,25 * *
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws
- as: ocp-e2e-metal-ipi-ovn-arm64
  cluster: build05
  steps:
    cluster_profile: equinix-ocp-metal
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      CLUSTERTYPE: virt-arm64
      NVME_DEVICE: ''
    workflow: baremetalds-e2e-ipv4
  cron: 3 2 6,22 * *
- as: ocp-e2e-upgrade-aws-arm64
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-initial
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
      TEST_SUITE: upgrade-conformance
    workflow: openshift-upgrade-aws
  cron: 38 10 7,23 * *
- as: ocp-installer-e2e-aws-ovn-arm64
  cron: 15 5 7,24 * *
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: ipi-aws-ovn
- as: ocp-image-ecosystem-aws-arm64
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-image-ecosystem
  cron: 48 10 9,15 * *
- as: ocp-jenkins-e2e-aws-arm64
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
      TEST_SUITE: openshift/jenkins-e2e-rhel-only
    workflow: openshift-e2e-aws
  cron: 5 1 9,17 * *
- as: ocp-e2e-serial-aws-arm64
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-serial
  cron: 52 3 6,15 * *
- as: ocp-e2e-ovn-serial-aws-arm64
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-ovn-serial
  cron: 36 6 7,16 * *
- as: ocp-e2e-aws-ovn-arm64
  cron: 56 4 6,24 * *
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-ovn
- as: ocp-e2e-aws-upi-arm64
  cron: 2 7 7,16 * *
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
      BOOTSTRAP_INSTANCE_TYPE: m6g.large
      COMPUTE_NODE_TYPE: m6g.xlarge
      MASTER_INSTANCE_TYPE: m6g.xlarge
      WORKER_INSTANCE_TYPE: m6g.xlarge
    workflow: openshift-e2e-aws-upi
- as: ocp-e2e-aws-arm64-single-node
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-single-node
  cron: 46 2 6,23 * *
- as: ocp-e2e-aws-arm64-techpreview
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-techpreview
  cron: 50 10 7,19 * *
- as: ocp-e2e-aws-arm64-techpreview-serial
  steps:
    cluster_profile: aws-arm64
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      BASE_DOMAIN: arm-ci.devcluster.openshift.com
    workflow: openshift-e2e-aws-techpreview-serial
  cron: 51 2 7,16 * *
- as: ocp-e2e-remote-libvirt-s390x
  cluster: build01
  cron: 30 3 6,16 * *
  steps:
    cluster_profile: libvirt-s390x
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: '4.11'
      NODE_TUNING: 'true'
      TEST_TYPE: conformance-parallel
    workflow: openshift-e2e-libvirt
- as: ocp-image-ecosystem-remote-libvirt-s390x
  cluster: build01
  cron: 27 6 8,24 * *
  steps:
    cluster_profile: libvirt-s390x
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: '4.11'
      TEST_TYPE: image-ecosystem
    workflow: openshift-e2e-libvirt
- as: ocp-jenkins-e2e-remote-libvirt-s390x
  cluster: build01
  cron: 38 6 6,19 * *
  steps:
    cluster_profile: libvirt-s390x
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: '4.11'
      TEST_TYPE: jenkins-e2e-rhel-only
    workflow: openshift-e2e-libvirt
- as: ocp-e2e-serial-remote-libvirt-s390x
  cluster: build01
  cron: 39 5 8,15 * *
  steps:
    cluster_profile: libvirt-s390x
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: '4.11'
      TEST_TYPE: conformance-serial
    workflow: openshift-e2e-libvirt
- as: ocp-e2e-compact-remote-libvirt-s390x
  cluster: build01
  cron: 59 9 5,18 * *
  steps:
    cluster_profile: libvirt-s390x
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: '4.11'
      MASTER_DISK: '64424509440'
      MASTER_MEMORY: '32768'
      TEST_TYPE: conformance-parallel
      WORKER_DISK: '64424509440'
      WORKER_MEMORY: '32768'
      WORKER_REPLICAS: '0'
    workflow: openshift-e2e-libvirt
- as: ocp-e2e-remote-libvirt-ppc64le
  cluster: build01
  cron: 51 10 8,24 * *
  steps:
    cluster_profile: libvirt-ppc64le
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:ppc64le-latest
    env:
      ARCH: ppc64le
      BRANCH: '4.11'
      TEST_TYPE: conformance-parallel
    workflow: openshift-e2e-libvirt
- as: ocp-image-ecosystem-remote-libvirt-ppc64le
  cluster: build01
  cron: 28 9 9,18 * *
  steps:
    cluster_profile: libvirt-ppc64le
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:ppc64le-latest
    env:
      ARCH: ppc64le
      BRANCH: '4.11'
      TEST_TYPE: image-ecosystem
    workflow: openshift-e2e-libvirt
- as: ocp-jenkins-e2e-remote-libvirt-ppc64le
  cluster: build01
  cron: 50 9 5,17 * *
  steps:
    cluster_profile: libvirt-ppc64le
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:ppc64le-latest
    env:
      ARCH: ppc64le
      BRANCH: '4.11'
      TEST_TYPE: jenkins-e2e-rhel-only
    workflow: openshift-e2e-libvirt
- as: ocp-e2e-serial-remote-libvirt-ppc64le
  cluster: build01
  cron: 6 2 10,18 * *
  steps:
    cluster_profile: libvirt-ppc64le
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:ppc64le-latest
    env:
      ARCH: ppc64le
      BRANCH: '4.11'
      TEST_TYPE: conformance-serial
    workflow: openshift-e2e-libvirt
- as: ocp-e2e-compact-remote-libvirt-ppc64le
  cluster: build01
  cron: 13 9 6,15 * *
  steps:
    cluster_profile: libvirt-ppc64le
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:ppc64le-latest
    env:
      ARCH: ppc64le
      BRANCH: '4.11'
      MASTER_DISK: '64424509440'
      MASTER_MEMORY: '32768'
      TEST_TYPE: conformance-parallel
      WORKER_DISK: '64424509440'
      WORKER_MEMORY: '32768'
      WORKER_REPLICAS: '0'
    workflow: openshift-e2e-libvirt
zz_generated_metadata:
  branch: master
  org: openshift
  repo: multiarch
  variant: nightly-4.11
