base_images:
  azure:
    name: ci-base
    namespace: azure
    tag: latest
  base:
    name: ubi
    namespace: ocp
    tag: '8'
  osde2e:
    name: osde2e
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: '4.13'
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rosa-classic-sts
  cron: 34 19 * * 6
  steps:
    env:
      CONFIGS: rosa,sts,stage,e2e-suite
      INSTALL_LATEST_NIGHTLY: '4.13'
      SECRET_LOCATIONS: /usr/local/osde2e-common,/usr/local/osde2e-trt-credentials
      SKIP_DESTROY_CLUSTER: 'true'
      SKIP_MUST_GATHER: 'true'
    post:
    - chain: gather
    - ref: osde2e-cleanup
    test:
    - ref: osde2e-test
- as: rosa-hcp
  cron: 26 16 * * 6
  steps:
    env:
      CONFIGS: hypershift
      INSTALL_LATEST_NIGHTLY: '4.13'
      SECRET_LOCATIONS: /usr/local/osde2e-common,/usr/local/osde2e-hypershift-credentials
      SKIP_DESTROY_CLUSTER: 'true'
      SKIP_MUST_GATHER: 'true'
    post:
    - chain: gather
    - ref: osde2e-cleanup
    test:
    - ref: osde2e-test
- as: osd-aws
  cron: 1 6 * * 7
  steps:
    env:
      CONFIGS: aws,stage,e2e-suite
      INSTALL_LATEST_NIGHTLY: '4.13'
      SECRET_LOCATIONS: /usr/local/osde2e-common,/usr/local/osde2e-trt-credentials
      SKIP_DESTROY_CLUSTER: 'true'
      SKIP_MUST_GATHER: 'true'
    post:
    - chain: gather
    - ref: osde2e-cleanup
    test:
    - ref: osde2e-test
- as: osd-gcp
  cron: 46 14 * * 6
  steps:
    env:
      CONFIGS: gcp,stage,e2e-suite
      INSTALL_LATEST_NIGHTLY: '4.13'
      SECRET_LOCATIONS: /usr/local/osde2e-common,/usr/local/osde2e-trt-credentials
      SKIP_DESTROY_CLUSTER: 'true'
      SKIP_MUST_GATHER: 'true'
    post:
    - chain: gather
    - ref: osde2e-cleanup
    test:
    - ref: osde2e-test
zz_generated_metadata:
  branch: main
  org: openshift
  repo: osde2e
  variant: nightly-4.13
